### ISSUE TITLE
Unable to update Telegram ID for an existing phone number

### ISSUE THREAD

**Issue by lamkeewei** [opengovsg/postmangovsg#1143]
**Describe the bug**

Currently, we only account for the case where a user with the same Telegram ID wants to update his/her number. This is done through the [query](https://github.com/opengovsg/postmangovsg/blob/9a1e4f7c18f5ba07966f0959df7f0300acfb7ef3/backend/src/telegram/utils/callback/handlers/contact.ts#L41) that updates the phone number if the Telegram ID already exists. However, the other scenario where the user has the same phone number but wants to change his Telegram ID is not handled. 

Insertion will result in a unique constraint conflict as the phone number is part of the primary key and has to be unique.

**To Reproduce**

1. Ensure that subscription is already captured in both `telegram_subscribers` and `bot_subscribers` table
2. Attempt to update the Telegram ID for the same phone number by making a POST to the `/callback/telegram/:botId` with the following payload:
```
{
   "message":{
      "from":{
         "id":[NEW TELEGRAM ID]
      },
      "contact":{
         "phone_number": "[OLD PHONE NUMBER]",
         "first_name": "John",
         "last_name": "Doe",
         "user_id":[NEW TELEGRAM ID]
      }
   }
}
3. An error should be thrown
```

**Expected behavior**

**Comment by zwliew** [comment]
Would it be reasonable to just delete the existing row containing the phone number before inserting the new row?

**Comment by zwliew** [comment]
Also a related question I have is: for telegram_subscribers, why was the phone number chosen to be the primary key instead of the telegram id?
