### ISSUE TITLE
[frontend tests] mock console functions globally in setupTests.ts

### ISSUE THREAD

**Issue by zwliew** [opengovsg/postmangovsg#1173]
**Problem**
Currently, we mock `console.error` statements in the tests where we expect it to be called. This prevents them from spamming stdout. This also allows us to directly see any `console.error` outputs from tests which aren't supposed to output them.

However, this results in a lot of unnecessary setup and teardown code in each test. A better solution is to mock console.error globally in `setupTests.ts`, and assert on the number of times it is called in each test.

Examples:
1. The [`displays the necessary elements`](https://github.com/opengovsg/postmangovsg/blob/201957cc04d7299edc04aa0eef77e8d8987f8d9c/frontend/src/components/dashboard/create/email/tests/EmailRecipients.test.tsx#L52) test does not mock `console.error` because it is not expected to be called in the test. If any `console.error` does output, we can easily tell what the issue is from the console output.

A better way to do this is to assert that `console.error` is not called: `expect(console.error).not.toBeCalled()`

2. The [`displays an error message after uploading an invalid recipients list`](https://github.com/opengovsg/postmangovsg/blob/201957cc04d7299edc04aa0eef77e8d8987f8d9c/frontend/src/components/dashboard/create/email/tests/EmailRecipients.test.tsx#L92) test mocks `console.error` because it is expected to be called. This way, the "spam" is silenced.

A better way to do this is to assert that `console.error` is called once: `expect(console.error).toBeCalledTimes(1)`

**Comment by tohhengxing** [comment]
Hi, is it possible for me to do this as an open source contribution?

**Comment by stanleynguyen** [comment]
> Hi, is it possible for me to do this as an open source contribution?

Hey yes please feel free to open a PR

**Comment by jhibberd-gov** [comment]
Moved to Notion.
