### ISSUE TITLE
Investigate which way of attaching images to emails is most widely supported by recipient clients

### ISSUE THREAD

**Issue by syan-syan** [opengovsg/postmangovsg#1181]
- what's used by Gmail, Mailchimp, Outlook and other common email client/providers
- what's supported and accepted by email and webmail clients

**Comment by jeantanzj** [comment]
Test sending 
- cid
- base64 inline embedded
- link
to the web and desktop clients of the top providers

**Comment by mjgui** [comment]
### All methods

- If the spam filter is triggered, usually all types of images are blocked by default in most clients

### Base64

- Pretty poorly supported (entirely blocked on Gmail, blocked by default on Gov emails without whitelist)

### CID

- Default method when users manually attach an image via the Gmail, Outlook web clients
- Seems to be not blocked by most clients, including Gmail, outlook.com, gov.sg email
- Main downside is increased email size

### External Images

- Most common method I found used by others (e.g. Gmail, Apple system emails; Surveymonkey newsletters, etc.) 
- Unblocked in most commercial email clients (unless the email trips up the spam filters)
- Might require some whitelisting for gov.sg emails

**Comment by pirsquare** [comment]
Linked image is the way to go. Many email clients only supports up to 20 MB payload so email may be dropped if you allow users to embed image. AFAIK, every email marketing software uses linked image these days.
