### ISSUE TITLE
Investigate select and delete/backspace not consistently working on the rich text editor

### ISSUE THREAD

**Issue by syan-syan** [opengovsg/postmangovsg#1194]
Observed that select text and delete on the rich text editor does not work consistently - using Google Chrome/MacOS. Occasionally instead of the entire block of text being deleted, only one letter within the block is deleted.

**Comment by lamkeewei** [comment]
@syan-syan do you have steps to repro the error?

**Comment by lamkeewei** [comment]
Removing prioritization as we can't repro.
