### ISSUE TITLE
Cannot upload using presigned URL

### ISSUE THREAD

**Issue by cakriwut** [opengovsg/postmangovsg#1205]
**Describe the bug**
After I retrieved presigned URL, I am not able to upload the file.
It always return unsigned payload.  

**To Reproduce**

1. Generate presigned url for the campaign, and copy the presigned_url
2. Using curl execute PUT command to presigned url, add Content-MD5 and Content-Type header.

**Expected behavior**
HTTP 200 OK, with etag

**Screenshots**
![image](https://user-images.githubusercontent.com/307755/119591487-47971980-be09-11eb-9ffe-be3606252468.png)

**Comment by lamkeewei** [comment]
@cakriwut, could you provide an example of the curl command that you've used? In addition, you may also refer to the [API usage docs](https://github.com/opengovsg/postmangovsg/blob/develop/docs/api-usage.md#3-upload-campaign-recipients) for an example on how to upload a recipient list to a presigned URL.

**Comment by cakriwut** [comment]
@lamkeewei 

```bash
 curl -i -v --location --request PUT https://s3.ap-southeast-1.amazonaws.com/file-production.postman.gov.sg/ff4dfc45-f282-4587-be87-f673053229e9\?VERY_LONG_TEXT --header 'Content-MD5: lmnfZgETY+oGC0IWCfaYOQ=='  --header 'Content-Type: text/csv' --data-binary '@/mnt/c/temp/postman_sample.csv'  

```

**Comment by lamkeewei** [comment]
@cakriwut I'm not able to reproduce this. Could you drop me an email at postman@open.gov.sg with more details (content of your recipient list, etc) about this API integration that you're doing?

**Comment by cakriwut** [comment]
I have found the issue - step 3.1 should use **urlencoded** of **thisisanexamplemd5checksum**.

In order to do that, in Bash we can do sed or install **gridsite-clients**
```bash
sudo apt-get install gridsite-clients
urlencode thisisanexamplemd5checksum
```

Then use the value to construct **https://api.postman.gov.sg/v1/campaign/100/upload/start?mime_type=text/csv&md5=encoded_thisisanexamplemd5checksum**

**Comment by cakriwut** [comment]
Incomplete documentation.
