### ISSUE TITLE
Support verification of custom from address using verified domain

### ISSUE THREAD

**Issue by lamkeewei** [opengovsg/postmangovsg#1208]
**Is your feature request related to a problem? Please describe.**
Currently as part of the custom from verification process, we lookup the Dkim attributes [using the email address](https://github.com/opengovsg/postmangovsg/blob/develop/backend/src/email/services/custom-domain.service.ts#L50-L57) as the identity. As we move towards verifying the entire domain, we should also allow using the domain as the identity used for looking up.

We are preserving the existing email address verification to support pre-existing custom from addresses that do not have verified domains.

Reference: [GetIdentityDkimAttributes](https://docs.aws.amazon.com/ses/latest/APIReference/API_GetIdentityDkimAttributes.html)

**Comment by syan-syan** [comment]
will close for now, if needed will likely take preferred approach of allowing entire agency to use single shared email address instead

**Comment by stanleynguyen** [comment]
As of current state of things, it's against our security recommendation to whitelist the whole domain. Will visit again with #1219 if this is back on the table
