### ISSUE TITLE
Inconsistent casing for APIs

### ISSUE THREAD

**Issue by mjgui** [opengovsg/postmangovsg#1245]
While most of our codebase is in `camelCase`, a number (but not all) of our JSON apis are in `snake_case`
(e.g. `/campaign/{id}/email/preview` vs `/campaign/{id}/upload/status`)

A number of the inconsistencies are caused by using shorthand property names when returning objects to JSON, instead of manually restating its children fields
e.g.
```js
const preview = {
  replyTo: ...,
  ...
}

res.json({
  preview
})
```

**Comment by jhibberd-gov** [comment]
Moved to Notion.
