### ISSUE TITLE
High volume campaigns and bounce mitigation

### ISSUE THREAD

**Issue by syan-syan** [opengovsg/postmangovsg#1265]
Problems
- unhalting campaigns still requires manual intervention
- this is more likely to happen with high volume campaigns, implying Postman cannot scale easily without manual intervention

Epic document https://docs.google.com/document/d/1LMUnoNQm1L-cA7yhqSL_uyDq7Hv9cRsYhR-D572Eioc/edit#

**Comment by mjgui** [comment]
https://docs.google.com/document/d/1BM4P0CS3bgNPUm6GzXJdmFFNeqM6bClh6ZZKqcFn5_8/edit#

**Comment by lamkeewei** [comment]
Done
