### ISSUE TITLE
Image upload error state

### ISSUE THREAD

**Issue by syan-syan** [opengovsg/postmangovsg#1288]
- Make list of image filetypes widely accepted by email clients
- Check images against this list and return error if not within the list 
- will advise error copy based on how long the list is

**Comment by mjgui** [comment]
**Attaching PDFs in src attribute of <img> tag**
Supported by iOS mail app, MacOS mail app,
Safari + all online clients such as Outlook.com (EXCEPT Gmail, which attempts to proxy all external images through their servers)
