### ISSUE TITLE
Outlook reply bug - first two sentences repeated when recipient replies

### ISSUE THREAD

**Issue by syan-syan** [opengovsg/postmangovsg#1304]
When recipient replies on Outlook, the first ~2 lines will be repeated above the header. This is similar to the bug MJ found before.

**Comment by tan-zx** [comment]
@stanleynguyen can close this one right? it's a feature and not a bug 😂 to get the preview to work properly?

**Comment by stanleynguyen** [comment]
> @stanleynguyen can close this one right? it's a feature and not a bug 😂 to get the preview to work properly?

Closing
