### ISSUE TITLE
Variable in email subject

### ISSUE THREAD

**Issue by syan-syan** [opengovsg/postmangovsg#1317]
Requested by user, not provided by Mail Merge / Outlook

**Comment by jeantanzj** [comment]
<img width="418" alt="Screenshot 2021-09-02 at 2 16 41 AM" src="https://user-images.githubusercontent.com/33819199/131722986-ce531631-76ce-4a6d-9f27-5a05615c7162.png">
We've always supported it

**Comment by syan-syan** [comment]
thanks my bad
