### ISSUE TITLE
Migrate EB env to Docker 3.4.10 running on AL2

### ISSUE THREAD

**Issue by prestonlimlianjie** [opengovsg/postmangovsg#1359]
Follow instructions:
https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/using-features.managing.clone.html

**Comment by stanleynguyen** [comment]
[Guide](https://docs.google.com/document/d/11F7CXveCLjarTG-zV-7LOligkeg5J2VnntlDElNZjVI/edit?usp=sharing)
