### ISSUE TITLE
Fix failing test suite for `sms-campaigns.routes.ts`

### ISSUE THREAD

**Issue by prestonlimlianjie** [opengovsg/postmangovsg#1386]
### Failed test suite for `sms-campaigns.routes.ts`
![Screenshot 2022-02-14 at 3 52 08 PM](https://user-images.githubusercontent.com/19917616/153822340-0b6e96f3-1349-45c8-aa6a-139bcec6a653.png)

**To Reproduce**

```
cd backend/
npm ci
npm run test
```

**Expected behavior**
All test suites should pass

**Comment by stanleynguyen** [comment]
Closing as this is part of #1387 and will be fixed by #1388
