### ISSUE TITLE
Deployment failure notifications from AWS Amplify

### ISSUE THREAD

**Issue by prestonlimlianjie** [opengovsg/postmangovsg#1403]
Currently, there is no deployment failure notification if AWS Amplify fails to deploy our frontend. Also investigate if EB/ECS triggers a deployment failure notification anywhere.

Possibly getting GitHub Actions to be the source of truth for deployment info; i.e. if deployment fails, the deploy step should reflect that. Is this possible? Otherwise, we might need to pipe notifications from AWS into Slack.

**Comment by stanleynguyen** [comment]
Done in #1565
