### ISSUE TITLE
Cypress Setup

### ISSUE THREAD

**Issue by stanleynguyen** [opengovsg/postmangovsg#1428]
Context: Smoke tests are currently manually carried out by the engineer who deploy new releases

DoD:
- [ ] Cypress test setup with a "hello world" test case
- [ ] Automated Github Action to run the test post-deployment on:
  - [ ] staging
  - [ ] production

**Comment by prestonlimlianjie** [comment]
Started working on this - ran into problems because my machine uses the M1 Mac chip. :(

Will attempt to hack my way around this.

> Currently, the way to run Cypress on Apple M1 ARM chip is by using Intel emulation with Rosetta 2, Apple's translation layer.

https://www.cypress.io/blog/2021/01/20/running-cypress-on-the-apple-m1-silicon-arm-architecture-using-rosetta-2/

**Comment by stanleynguyen** [comment]
Resolved in #1538
