### ISSUE TITLE
Reduce CPU utilisation when verifying authenticity of webhook requests

### ISSUE THREAD

**Issue by lamkeewei** [opengovsg/postmangovsg#1437]
**Is your feature request related to a problem? Please describe.**

**Twilio callbacks**
Currently, when sending out SMSes using Twilio, we use `bcrypt` to generate the password for our callback URLs.

https://github.com/opengovsg/postmangovsg/blob/648c3da5e700fc6e96d580f18db28f8ad3872e37/worker/src/sms/services/twilio-client.class.ts#L79

This means that for each webhook callback that we receive we will need to carry out a relatively CPU intensive comparison to verify that the provided password is correct. 

https://github.com/opengovsg/postmangovsg/blob/648c3da5e700fc6e96d580f18db28f8ad3872e37/backend/src/sms/services/sms-callback.service.ts#L26

This is the main bottleneck for our callback servers when large SMS campaigns are sent out. 

**SES callbacks**
For email campaigns, the bottleneck is at the signature validation for each delivery status SNS message from SES. This involves a quite expensive asymmetric crypto operation. We've profiled this previously and identified this as the bottleneck. 

https://github.com/opengovsg/postmangovsg/blob/648c3da5e700fc6e96d580f18db28f8ad3872e37/backend/src/email/utils/callback/parsers/ses.ts#L103

**Describe the solution you'd like**
For Twilio, I think there are two ways to solve this:
1. Use a cheaper hash function (SHA1/2) to hash the password
2. Get rid of the password authentication completely and just rely on [Twilio's `X-Twilio-Signature` header](https://www.twilio.com/docs/usage/webhooks/webhooks-security#validating-signatures-from-twilio)

For SES:
- We might want to consider if we can use a simpler method of verifying the authenticity of the webhook request. Perhaps we can also rely on a HMAC in a custom SMTP header.

**Comment by stanleynguyen** [comment]
bcrypt benchmark result (with scripts used for benchmarking)
```js
function printMemoryUsed() {
  const used = process.memoryUsage()
  for (let key in used) {
    console.log(
      `${key} ${Math.round((used[key] / 1024 / 1024) * 100) / 100} MB`
    )
  }
}
;(async function main() {
  const bcrypt = require('bcrypt')
  const password =
    'postman@open.gov.sg123456WaferMushinessTrollingChowderBreweryStack'
  //   const hash = await bcrypt.hash(password, 10)
  //   console.log(hash)
  //   printMemoryUsed()
  bcrypt.compareSync(
    password,
    '$2b$10$kpz4UYULJoVagvdbkjtXBepz15z1C681995Ji0IunX.28rPxYVw9.'
  )
  printMemoryUsed()
})()
```

```
rss 34.94 MB
heapTotal 7.17 MB
heapUsed 5.46 MB
external 0.83 MB
arrayBuffers 0.03 MB
```

**Comment by stanleynguyen** [comment]
md5 benchmark result

```js
// script used for benchmarking
function printMemoryUsed() {
  const used = process.memoryUsage()
  for (let key in used) {
    console.log(
      `${key} ${Math.round((used[key] / 1024 / 1024) * 100) / 100} MB`
    )
  }
}

const crypto = require('crypto')
const password =
  'postman@open.gov.sg123456WaferMushinessTrollingChowderBreweryStack'
// const hash = crypto.createHash('md5').update(password).digest('hex')
// console.log(hash)
// printMemoryUsed()
const hashForCompare = crypto.createHash('md5').update(password).digest('hex')
'63f6e545e9bff297707d841b653ba31f' === hashForCompare
printMemoryUsed()
```

```
rss 27.34 MB
heapTotal 4.67 MB
heapUsed 3.89 MB
external 0.36 MB
arrayBuffers 0.02 MB
```

**Comment by stanleynguyen** [comment]
Given the significant performance boost we can get from using MD5, and how short-lived this hash usage is for (maximum ~2 hours from when we send til when we get a callback), we will be replacing bcrypt with md5

**Comment by stanleynguyen** [comment]
Baseline benchmark

```js
function printMemoryUsed() {
  const used = process.memoryUsage()
  for (let key in used) {
    console.log(
      `${key} ${Math.round((used[key] / 1024 / 1024) * 100) / 100} MB`
    )
  }
}
printMemoryUsed()
```

```
rss 25.61 MB
heapTotal 4.67 MB
heapUsed 3.73 MB
external 0.2 MB
arrayBuffers 0.01 MB
```

**Comment by stanleynguyen** [comment]
@lamkeewei For SES, wdyt if we just put a similar password (as sms one) inside the `X-SMTPAPI` header since it's just a stringified JSON anyway?

**Comment by stanleynguyen** [comment]
benchmarking using `crypto` sha256 vs md5
```
// script used for benchmarking
function printMemoryUsed() {
  const used = process.memoryUsage()
  for (let key in used) {
    console.log(
      `${key} ${Math.round((used[key] / 1024 / 1024) * 1000000) / 1000000} MB`
    )
  }
}

const crypto = require('crypto')
const password =
  '***'
// const hash = crypto.createHash('sha256').update(password).digest('hex')
// console.log(hash)
// printMemoryUsed()
const hashForCompare = crypto
  .createHash('sha256')
  .update(password)
  .digest('hex')
'91c1003fb15d4f49248a2d730cdfe28542f8980966e78efc909bfee30d81b7d2' ===
  hashForCompare
printMemoryUsed()
```

```
rss 27.828125 MB
heapTotal 4.671875 MB
heapUsed 3.891678 MB
external 0.355903 MB
arrayBuffers 0.016489 MB
```

```
// script used for benchmarking
function printMemoryUsed() {
  const used = process.memoryUsage()
  for (let key in used) {
    console.log(
      `${key} ${Math.round((used[key] / 1024 / 1024) * 1000000) / 1000000} MB`
    )
  }
}

const crypto = require('crypto')
const password =
  '***'
// const hash = crypto.createHash('md5').update(password).digest('hex')
// console.log(hash)
// printMemoryUsed()
const hashForCompare = crypto.createHash('md5').update(password).digest('hex')
'63f6e545e9bff297707d841b653ba31f' === hashForCompare
printMemoryUsed()

```

```
rss 27.28125 MB
heapTotal 4.671875 MB
heapUsed 3.891655 MB
external 0.355903 MB
arrayBuffers 0.016489 MB
```
