### ISSUE TITLE
Update disaster recovery documentation

### ISSUE THREAD

**Issue by lisatjide** [opengovsg/postmangovsg#1452]
In response to the recent Twilio incident.
- Document contingency workflow that can be triggered for similar incidents 
- This could include banner updates, sending an email notification to all users notifying them of the issue

- [ ] Include instructions on how to put up banner

**Comment by prestonlimlianjie** [comment]
Created incident response guide: https://docs.google.com/document/d/1SuFmMfkA5u3APITLsr8GjuYI5SlQqJAjgSNJ3UtlWyA
