### ISSUE TITLE
Script for failover to another SMS provider for urgent/important campaigns

### ISSUE THREAD

**Issue by lisatjide** [opengovsg/postmangovsg#1453]
**Is your feature request related to a problem? Please describe.**
During Twilio incidents, there might be important SMS messages that needs to be sent out. It will take a long time for agencies to procure another provider due to complicated procurement process. 

To ensure that these campaigns is sent out, Postman will help them send out these messages through another provider. 
A simple script could be written to override the sending of selected campaign using credentials of another provider

DoD
- [ ] Script 
- [ ] Set aside budget and procure another provider
- [ ] Check whether SNS can be whitelisted on Approved Aggregator list @samuelKSE @lisatjide 
- [ ] Check why we get quota limit error

**Comment by prestonlimlianjie** [comment]
Had a discussion with @lamkeewei - he had a few points
- Play around with the MessageBird UI; during the last Twilio outage, the previous PM could upload a CSV onto the MessageBird UI directly to send SMSes out. So perhaps there is no need for such a script.
- We could explore a secondary SMS provider integration but maybe start with an OGP-only transactional API endpoint

**Comment by samuelKSE** [comment]
Follow up with SGNIC on this

**Comment by samuelKSE** [comment]
I have emailed SGNIC to check in on their progress with registering Amazon SNS. If talks have not started, I was thinking we can start this conversation with Amazon SNS and link them up with SGNIC.

**Comment by stanleynguyen** [comment]
@prestonlimlianjie so apparently we couldn't send SMS using SNS previously because we didn't have production access (idk why their documentation says that we could). I've managed to send messages with production access in place. We're good to go.
