### ISSUE TITLE
simplify user & campaign db querying for prod ops

### ISSUE THREAD

**Issue by lisatjide** [opengovsg/postmangovsg#1471]
**Is your feature request related to a problem? Please describe.**
Product ops has to rely on engineers to query for problematic campaigns or identify owner of a specific campaigns.
Current method: setup DB access (guide [here](https://docs.google.com/document/d/1tAUK6N85nlDUG9_kWtU8RqlUk38m8J5UScKeIPgaeKU/edit#heading=h.8tec0vsw046e)) and do a SQL query directly on the DB (guide [here](https://docs.google.com/document/d/1_1VzdcjU49KEFUi3xZhwSIq4b5yfhjfxWSbmJB0O2K0/edit#)) 

Issues with current way of querying DB:
- Setup process is tedious, hard to onboard new user 
- Hard to extract top campaigns or users without additional computation, require eng help to extract (for reporting - e.g top campaigns or users)
- Large query will run the risk of bringing down the DB
- Risk of keeping and losing the key

**Describe the solution you'd like**
- Create a read replica of the DB for ops querying (need not be real time but close enough for troubleshooting
- In term of reading the DB, there could be a few ways
1. Write default script to query for information such as campaign owner, campaign title [DONE] 
2. Use postman for easy query through fixed script
- For reporting 
1. Dashboard to track growth?

**Comment by lisatjide** [comment]
consider using https://retool.com/

**Comment by stanleynguyen** [comment]
Some findings:
- Retool: Clunky but has SSH tunnelling hence compatible with our current setup
- Budibase: doesn't seem to have SSH tunnelling, so if we're to use this we will probably setup a proxy instance with port 5432 open

**Comment by tan-zx** [comment]
start with one query: how many campaigns of each channel created today (assume daily run)

**Comment by stanleynguyen** [comment]
> start with one query: how many campaigns of each channel created today (assume daily run)

Some of the queries that we used previously are [here](https://docs.google.com/document/d/1_1VzdcjU49KEFUi3xZhwSIq4b5yfhjfxWSbmJB0O2K0/edit#) if you need something to start with

**Comment by lisatjide** [comment]
going to create a new issue on creating read replica for db poking since we agreed that we dont' want to query or poke prod db

**Comment by tan-zx** [comment]
Closing this as it's solved by Grafana dashboards
