### ISSUE TITLE
Investigate the relevance and UX of Telegram channel

### ISSUE THREAD

**Issue by lisatjide** [opengovsg/postmangovsg#1502]
Current major user - RSAF 
- Frequent reporting of issues
- Low take up

**Comment by samuelKSE** [comment]
Issues: 
- New users subscribing to the Telegram bot will not automatically receive new Telegram messages sent through the campaign until the mailing list is manually updated
- Flow is as such - users email us to check why they haven't been receiving messages, we email RSNPost admin with the emails, they update their campaign - this is super janky
- Current message sending is also one way with no way to monitor replies to the messages
