### ISSUE TITLE
Flaky test sms-campaign.routes.test.ts

### ISSUE THREAD

**Issue by tan-zx** [opengovsg/postmangovsg#1505]
`sms-campaign.routes.test.ts` is known to be flaky (sometimes passes, sometimes fails)

![image](https://user-images.githubusercontent.com/67887489/165473609-1eeeafcd-696d-4baf-8fe4-d8935fe7d8f8.png)

To-do:
- [ ]  Reliably reproduce the failure
- [ ]  Fix the test

@stanleynguyen lmk if this seems right or if there's any other additional info to add!

**Comment by stanleynguyen** [comment]
not happening as of lately
