### ISSUE TITLE
use ogp footer 

### ISSUE THREAD

**Issue by lisatjide** [opengovsg/postmangovsg#1507]
postman's footer is not the standard ogp footer. once ogp footer is updated, we should use it

**Comment by sarahsalim** [comment]
@stanleynguyen  
Figma file [here](https://www.figma.com/file/29FkTqWnA4yLKzstnvyY6X/%F0%9F%91%91-Design-Master?node-id=8206%3A44133) for your reference. Both desktop and mobile.

I think Form team must have already coded the footer components when working on OGP Base Design System. Do check in with them first!

The new OGP footer follows a new desktop grid. I guess as long as the section above the footer is aligned, it should be alright. Don't want to make too many unnecessary UI changes for now as things will change soon with V2 in 2023! Thank you!

**Comment by lisatjide** [comment]
@stanleynguyen any idea why we closed this?
