### ISSUE TITLE
Multiple line breaks not working as expected

### ISSUE THREAD

**Issue by tan-zx** [opengovsg/postmangovsg#1508]
So I'm testing out Postman as part of my onboarding.

I was trying out multiple line breaks in the editor and it seems like this is somehow collapsed into a single line break in the eventual email.

Probably no big deal, but just thought it seems like a bug that defies user expectations. 

![SCR-20220428-gvx](https://user-images.githubusercontent.com/67887489/165674967-ebf9f36c-dead-4580-a6a6-d589bf0ae151.png)

![SCR-20220428-gvn](https://user-images.githubusercontent.com/67887489/165675028-ec1dc09a-adde-4649-9973-1223c87783f2.png)

**Comment by lisatjide** [comment]
thanks for raising this, suggest we add this into our guide to clear any misunderstanding @samuelKSE .
makes sense to not allow extra spacing because it's not good readability practice

**Comment by stanleynguyen** [comment]
Intended behaviour as mentioned in #1626
