### ISSUE TITLE
Miscellaneous errors on Landing page

### ISSUE THREAD

**Issue by tan-zx** [opengovsg/postmangovsg#1511]
<img width="735" alt="image" src="https://user-images.githubusercontent.com/67887489/165915933-3aa2048b-23c9-4b92-8bef-cf43306fe27e.png">

To investigate subsequently; doesn't seem to impact functionality

**Comment by stanleynguyen** [comment]
![Screenshot 2022-06-23 at 11 31 27 AM](https://user-images.githubusercontent.com/12974927/175203205-94d82e21-0bef-4a45-bc7f-043b72f0bb9c.png)

The error above only happens due to missing migration in local setup
