### ISSUE TITLE
reconfigure Sentry and AWS alerts

### ISSUE THREAD

**Issue by tan-zx** [opengovsg/postmangovsg#1519]
# Sentry

Slack integration expired after Sentry Business Plan trial has expired — currently on Developer Plan. Need to upgrade to Team or Business Plan to re-enable this integration.

To do:
- [ ] Look into which plan serves our needs
- [ ] Upgrade to the correct plan and re-configure alerts + re-enable Slack integration

# AWS alerts

#postman-aws-alerts Slack channel has recently been overactive with alerts.

To do:
- [ ] Look into alerts to see if further action required
- [ ] If necessary, recalibrate alert thresholds to avoid false positives

**Comment by lisatjide** [comment]
AOR for Sentry raised on 13 May, pending approval
