### ISSUE TITLE
Deprecating CloudWatch

### ISSUE THREAD

**Issue by stanleynguyen** [opengovsg/postmangovsg#1529]
As we're moving to Datadog, we can deprecate our Cloudwatch usage

DoD:
- [ ] Remove cloudwatch loader
- [ ] Remove all related cloudwatch dependencies

**Comment by lisatjide** [comment]
why do we want to move to datadog?

**Comment by stanleynguyen** [comment]
> why do we want to move to datadog?

- We want to consolidate all of our observability into a single platform so we can correlate them easily (i.e. datadog help us visualise the traces with logs embedded into the information tabs)
- It's easier to search and view logs from dd dashboard
