### ISSUE TITLE
Update all links to gogovsg for easy updating in the future

### ISSUE THREAD

**Issue by lisatjide** [opengovsg/postmangovsg#1540]
<img width="733" alt="Screenshot 2022-05-17 at 5 22 53 PM" src="https://user-images.githubusercontent.com/23736580/169931846-cbc05a4c-a18c-44bc-b47f-ef827e58c9c5.png">
("What is this?" text under SMS button)

Currently points to the guide page directly, created go.gov.sg link for ease of updating: https://go.gov.sg/postman-guide-sms

All gogovsg links will be kept on postman@open.gov.sg accounts

**Comment by stanleynguyen** [comment]
It's pointing to [our own guidebook](https://guide.postman.gov.sg/quick-start/sms#find-twilio-credentials-on-twilio-console) though so I don't think we need to use go gov?

**Comment by stanleynguyen** [comment]
There're a bunch of other guide links as well. Do we wanna update them all to gogov?
```
REACT_APP_GUIDE_SMS_CREDENTIALS_URL='https://guide.postman.gov.sg/guide/getting-started/sms#find-twilio-credentials-on-twilio-console'
REACT_APP_GUIDE_SMS_ACCOUNT_SID_URL='https://guide.postman.gov.sg/guide/quick-start/sms#step-1-account-sid-and-auth-token'
REACT_APP_GUIDE_SMS_API_KEY_URL='https://guide.postman.gov.sg/guide/quick-start/sms#step-2-set-up-a-standard-api-key'
REACT_APP_GUIDE_SMS_MESSAGING_SERVICE_URL='https://guide.postman.gov.sg/guide/quick-start/sms#step-3-set-up-your-messaging-service'
REACT_APP_GUIDE_TELEGRAM_CREDENTIALS_URL='https://guide.postman.gov.sg/guide/getting-started/telegram-bot'
REACT_APP_GUIDE_POWER_USER_URL='https://guide.postman.gov.sg/guide/power-users'
REACT_APP_CONTACT_US_URL='https://go.gov.sg/postman-contact-us'
REACT_APP_CONTRIBUTE_URL='https://github.com/opengovsg/postmangovsg'
REACT_APP_PRIVACY_URL='https://guide.postman.gov.sg/privacy.html'
REACT_APP_TC_URL='https://guide.postman.gov.sg/t-c.html'
REACT_APP_REPORT_BUG_URL='https://guide.postman.gov.sg/report-bug.html'
```

**Comment by lisatjide** [comment]
Yes! Updated list!
```
REACT_APP_GUIDE_SMS_CREDENTIALS_URL='https://go.gov.sg/postman-guide-sms'
REACT_APP_GUIDE_SMS_ACCOUNT_SID_URL='https://go.gov.sg/postman-sms-twilio-sid'
REACT_APP_GUIDE_SMS_API_KEY_URL='https://go.gov.sg/postman-api-setup'
REACT_APP_GUIDE_SMS_MESSAGING_SERVICE_URL='https://go.gov.sg/postman-sms-setup'
REACT_APP_GUIDE_TELEGRAM_CREDENTIALS_URL='https://go.gov.sg/postman-telegram-setup'
REACT_APP_GUIDE_POWER_USER_URL='https://go.gov.sg/postman-power-user'
REACT_APP_LOGIN_EMAIL_TEXT='Sign in with your .gov.sg email' >> NOT UPDATED
REACT_APP_LOGIN_EMAIL_PLACEHOLDER='e.g. postman@agency.gov.sg' >> NOT UPDATED
REACT_APP_CONTACT_US_URL='https://go.gov.sg/postman-contact-us'
REACT_APP_CONTRIBUTE_URL='https://go.gov.sg/postman-github'
REACT_APP_PRIVACY_URL='https://go.gov.sg/postman-privacy'
REACT_APP_TC_URL='https://go.gov.sg/postman-tnc'
REACT_APP_REPORT_BUG_URL='https://go.gov.sg/postman-report-bug'
```

**Comment by lisatjide** [comment]
#: config.ts:67
msgid "link.guideEmailPasswordProtectedUrl"
msgstr "https://go.gov.sg/postman-password-protected-email-guide"

#: config.ts:73
msgid "link.guidePowerUserUrl"
msgstr "https://go.gov.sg/postman-power-users"

#: config.ts:75
msgid "link.guideRemoveDuplicatesUrl"
msgstr "https://go.gov.sg/postman-remove-dups-excel"

#: config.ts:69
msgid "link.guideSmsAccountSidUrl"
msgstr "https://go.gov.sg/postman-sms-acc-sid"

#: config.ts:70
msgid "link.guideSmsApiKeyUrl"
msgstr "https://go.gov.sg/postman-sms-standard-api-key"

#: config.ts:71
msgid "link.guideSmsMessagingServiceUrl"
msgstr "https://go.gov.sg/postman-sms-messaging-service"

#: config.ts:68
msgid "link.guideSmsUrl"
msgstr "https://go.gov.sg/postman-sms-creds"

#: config.ts:72
msgid "link.guideTelegramUrl"
msgstr "https://go.gov.sg/postman-telegram-bot"

#: config.ts:66
msgid "link.guideUrl"
msgstr "https://guide.postman.gov.sg/"

#: config.ts:79
msgid "link.privacyUrl"
msgstr "https://go.gov.sg/postman-privacy"

#: config.ts:80
msgid "link.reportBugUrl"
msgstr "https://go.gov.sg/postman-report-bug"

#: config.ts:78
msgid "link.tncUrl"
msgstr "https://go.gov.sg/postman-legal-tnc"
