### ISSUE TITLE
replace joi/celebrate with openapi-based validator

### ISSUE THREAD

**Issue by lisatjide** [opengovsg/postmangovsg#1542]
instead of using joi/celebrate to validate and swagger/openapi to document, it's easier and less work to do both using openapi standards
- a single source of truth
- the docs will always be up-to-date with the code

This also makes it easier for API users to onboard and follow our documentation

**Comment by stanleynguyen** [comment]
https://github.com/cdimascio/express-openapi-validator for the validator
