### ISSUE TITLE
Separating NODE_ENV and APP_ENV

### ISSUE THREAD

**Issue by stanleynguyen** [opengovsg/postmangovsg#1550]
Currently, we're using `NODE_ENV` for our app environment. However, as `NODE_ENV` can [affect how applications behave](https://nodejs.dev/learn/nodejs-the-difference-between-development-and-production), this is a disparity between non-production (e.g. staging) and production environment

Solution: Use `APP_ENV` to replace all current usage of `NODE_ENV` and default `NODE_ENV=production` on all non-local environments

**Comment by jhibberd-gov** [comment]
Moved to Notion.
