### ISSUE TITLE
import postman user queries into csv or google sheets

### ISSUE THREAD

**Issue by lisatjide** [opengovsg/postmangovsg#1552]
**Is your feature request related to a problem? Please describe.**
currently all user queries are submitted through [go.gov.sg/postman-contact](https://go.gov.sg/postman-contact-us) using formsg email mode. there is no way for us to collate these queries into a csv/spreadsheet

however, it is difficult to track these queries and understand what are the top pressing issues that users are facing currently as we do not log these queries in a structured manner. 

**Describe the solution you'd like**
Pull emails from postman@open.gov.sg formsg submissions and export it into google sheets/csv. 
**Note:** only look at formsg submissions, not direct emails at this point

This is likely a one time effort to pull older data since we've decided to move to Zendesk to ease of user query tracking.

**Comment by prestonlimlianjie** [comment]
@lisatjide is the form in storage mode?

**Comment by lisatjide** [comment]
not in storage mode. it's in email mode. thanks rae for your help in this!
