### ISSUE TITLE
Telegram bot does not respond when user subscribe to their own bot

### ISSUE THREAD

**Issue by lisatjide** [opengovsg/postmangovsg#1564]
**Describe the bug**
After user created the bot using BotFather, when user click start, nothing happens. 
<img width="568" alt="Screenshot 2022-06-03 at 11 54 43 AM" src="https://user-images.githubusercontent.com/23736580/171782908-f479ffc4-99fd-457f-926f-f5274c68ec36.png">
<img width="753" alt="Screenshot 2022-06-03 at 11 54 22 AM" src="https://user-images.githubusercontent.com/23736580/171784033-9a1795fe-2f1c-4b16-bf77-0753e1f55b4d.png">

**To Reproduce**
Go through the Telegram bot setup on BotFather and try sending a message to your bot.

**Comment by gohsjvanessa** [comment]
Hi, I have the same issue where the agency bot does not prompt with the "Register phone number" that it should. Telegram bot credentials have been saved to Postman before attempting to register details on the agency bot. Have verified that personal account privacy settings allow for 'Everyone' to see phone number. Behaviour persists with new bots.

**Comment by stanleynguyen** [comment]
The bug is [here](https://github.com/opengovsg/postmangovsg/blob/08da008200a75721bf0a23283f65409ad2e89d2d/backend/src/telegram/services/telegram-callback.service.ts#L19-L22) as we've updated the credential name convention to include env name as well in this PR #1414
