### ISSUE TITLE
Run tests as part of pre-push hook?

### ISSUE THREAD

**Issue by tan-zx** [opengovsg/postmangovsg#1584]

**Comment by stanleynguyen** [comment]
Would take too long just to make a commit. It should be the implementer's responsibility to run tests to ensure if he/she needs to.

Either way we would still need to have the tests on our CI as the final check so this will only make a diff in the local dev (outlined above)

**Comment by tan-zx** [comment]
Oh was thinking it could only be run before pushing to remote, rather than on every commit, I think CheckFirst does this.

**Comment by stanleynguyen** [comment]
> Oh was thinking it could only be run before pushing to remote, rather than on every commit, I think CheckFirst does this.

Yea would take too long to push to remote lol. I personally would `--no-verify` so I don't have to wait for these tests. imo hooks should be simple enough that we can quickly do git actions that we can so we should keep them to just the essentials (i.e. those that once incorrectly committed or pushed would require reversal like linting and detecting secrets)

**Comment by tan-zx** [comment]
Good point!
