### ISSUE TITLE
Developer can reuse project

### ISSUE THREAD

**Issue by jeantanzj** [opengovsg/postmangovsg#16]
Developer wants to reuse project (either template or csv)

POST /project/{projectId}/reset 

- only available via api key
- Ensure no jobs in job_queue for this project, or any existing job for this project is in LOGGED state
- Remove any existing jobs in job_queue
- Set project.valid to false

**Comment by xming13** [comment]
I can help if this issue is still relevant.

**Comment by pettypychen** [comment]
Closing this issue since it is deprioritised
