### ISSUE TITLE
Move non-sensitive/secret GitHub Actions env variables out and use conditional instead

### ISSUE THREAD

**Issue by tan-zx** [opengovsg/postmangovsg#1642]
currently, there are env variables that are not secret but added to GitHub Actions as a secret so that we can deploy them separately for staging and production.

this is bad because these are not meant to be secret, yet they are encrypted. this makes it harder to understand the codebase.

to fix: use if condition inside GitHub `.yml` workflows

**Comment by stanleynguyen** [comment]
Done in #1897
