### ISSUE TITLE
Unsub link not clickable for yahoo mail users

### ISSUE THREAD

**Issue by yingyee0111** [opengovsg/postmangovsg#1645]
**Describe the bug**
The unsub link that is supposed to be embedded on the word "here" is greyed out and not clickable for yahoo mail recipients.

**Expected behavior**
Clicking on the word "here" should lead to the unsub page.

**Screenshots**
<img width="712" alt="Screenshot 2022-06-29 at 9 41 45 PM" src="https://user-images.githubusercontent.com/33883582/176451145-a34cb859-63c7-4a57-9144-502ae0f0a28f.png">

**Comment by tan-zx** [comment]
@yingyee0111 seems like it won't auto-close if you put a bracket around the issue haha
<img width="121" alt="image" src="https://user-images.githubusercontent.com/67887489/176586050-3e059fe1-0831-481a-a796-b9d73f351be0.png">
