### ISSUE TITLE
allow multiple emails in reply-to

### ISSUE THREAD

**Issue by lisatjide** [opengovsg/postmangovsg#1659]
**Is your feature request related to a problem? Please describe.**
when speaking to one of the users, he mentioned that the reason why he needed to cc is because he wanted the email responses to go to multiple people in his team. 

**Describe the solution you'd like**
to solve this problem, user requested for cc feature but we can also solve this by allowing multiple emails in reply-to. 
when a recipient replies to an email, it will be sent to everyone in the reply-to section. similar to how form responses is sent to multiple people.

**Comment by stanleynguyen** [comment]
Question before I forget: Is the UI gonna be something like the add tags features in social media (i.e. the whitespace and/or comma character will confirm an entry)
