### ISSUE TITLE
update Postman guide

### ISSUE THREAD

**Issue by lisatjide** [opengovsg/postmangovsg#1663]
a few things we can look at updating

- [x] Guide to Postman editor (shift + enter vs enter, usage of colors, headers)
- [x] Unsubscribe guidelines and what it means

**Comment by tan-zx** [comment]
can look at this [Notion page](https://www.notion.so/opengov/List-of-nits-in-Postman-Guide-43fac23659aa451bb4acd9efd3a430ca) too @kendra-wong

**Comment by lisatjide** [comment]
closing this since this is an ongoing task
