### ISSUE TITLE
Refactor `get_messages_to_send_email_with_agency` SQL function

### ISSUE THREAD

**Issue by prestonlimlianjie** [opengovsg/postmangovsg#1682]
### Problem

The SQL function `get_messages_to_send_email_with_agency` currently does too many things. [[Code reference](https://github.com/opengovsg/postmangovsg/blob/9422bb20e3408025bdb01d914be74b7bb80c6614/backend/src/database/migrations/20210701040855-create-get-messages-to-send-email-with-agency-function.js)]

It does two major things:
1. It selects X (where X is the rate) number of records in the `email_ops` table belonging to a specific campaign and sets the `sent_at` value to `NOW()`
2. At the end of the SQL function, it sets the `job_queue` status belonging to a specific campaign to `SENT` (from `SENDING`) if there are no more records in the `email_ops` table belonging to that campaign where the `status` is `NULL`.

The problem with this implementation is that it obscures the very important second step.

### Solution

We should refactor the SQL function such that it only does step 1, and create an entirely new SQL function that does step 2. Let's call step 1 and step 2 `set_email_ops_sent_at_to_now` and `set_job_status_to_sent_if_all_emails_have_been_processed` respectively. Please feel free to suggest better names if you have any in mind.

At present, we call `get_messages_to_send_email_with_agency` (via `getMessages()`) in a while loop in the `enqueueAndSend()` method. However, we can refactor `enqueueAndSend()` such that we:
- call `set_email_ops_sent_at_to_now` in the while loop
- call `set_job_status_to_sent_if_all_emails_have_been_processed` after the while loop

This way, we make the call to step 2 clearer.

**Comment by jhibberd-gov** [comment]
Moved to Notion.
