### ISSUE TITLE
Tighten TypeScript setting of data models 

### ISSUE THREAD

**Issue by tan-zx** [opengovsg/postmangovsg#1696]
Flowing from https://github.com/opengovsg/postmangovsg/pull/1695#issue-1303088974, to tighten TypeScript settings of data models (Sequelize has much better TypeScript support compared to when postmangovsg was first written)

As discussed [here](https://github.com/opengovsg/postmangovsg/pull/1695#issuecomment-1184144050), can set set `"strictPropertyInitialization": false` in `tsconfig.json` too.

**Comment by tan-zx** [comment]
TODO:
- Noticed that columns that should have unique constraint (e.g. `users.email`, `email_from_address.email`) do not have them → this is quite dangerous, especially in light of `add_user` function (see [this](https://github.com/opengovsg/postmangovsg/issues/1713#:~:text=add_user%20was%20a%20utility%20method%20to%20add%20someone%20that%20was%20not%20of%20whitelisted%20email%20domain%20%E2%86%92%20we%20shall%20retain%20this%20in%20a%20database%20migration%20and%20annotate%20clearly%20that%20it%20is%20meant%20to%20be%20triggered%20manually%20(and%20hence%20not%20invoked%20directly%20in%20the%20codebase)))
- Generally, would be good to go through models and tighten them up

**Comment by jhibberd-gov** [comment]
Moved to Notion.
