### ISSUE TITLE
modal behavior is wrong

### ISSUE THREAD

**Issue by tan-zx** [opengovsg/postmangovsg#1700]
![image](https://user-images.githubusercontent.com/67887489/179175846-628296af-c987-4202-9b7b-ca6df7c6c733.png)

when editing campaign name, if I select the text with my mouse and release the click outside the modal (i.e. in the blue area), the entire modal is closed

this is buggy behavior (should only close if click + release are outside of modal)

**Comment by jhibberd-gov** [comment]
Moved to Notion.
