### ISSUE TITLE
Flaky frontend test

### ISSUE THREAD

**Issue by tan-zx** [opengovsg/postmangovsg#1767]
Originally encountered on 2022-09-15: https://github.com/opengovsg/postmangovsg/actions/runs/3057519891/jobs/4932758414

Subsequent encounters: 
- https://github.com/opengovsg/postmangovsg/actions/runs/3149787004/jobs/5121812777
- https://github.com/opengovsg/postmangovsg/actions/runs/3217106208/jobs/5259704605

Low priority, to fix when we have time

**Comment by jhibberd-gov** [comment]
Moved to Notion.
