### ISSUE TITLE
Rationalise database permissions (low priority)

### ISSUE THREAD

**Issue by tan-zx** [opengovsg/postmangovsg#1772]
Discussed with @prestonlimlianjie, identified issue in light of [this](https://github.com/opengovsg/postmangovsg/pull/1768#issuecomment-1250031351).

Basically, what's happening right now is:
- When a new table is created, permission needs to be manually granted in Postgres to `flamingo_iam` user
- This is a bit of an annoyance — if we want to manage access to the db, it's better to do so on the application-level (e.g. some users can only write to certain tables) or on the infra-level (e.g. for applications with read-only access, connect to the Aurora read replica)

Solution:
- For the backend, the db user should be able to read and write all tables by default (without the need to manually grant permissions)
- This is low priority for now, since we can just get around this problem by knowing to grant permissions each time we complete a feature that involves creating a new table.

**Comment by jhibberd-gov** [comment]
Moved to Notion.
