### ISSUE TITLE
Exclude unnecessary fields from request to enable Datadog indexing

### ISSUE THREAD

**Issue by tan-zx** [opengovsg/postmangovsg#1788]
> All request and responses are logged rn so it shouldn't be an issue. The only potential problem is that we're logging the whole request including the file field - rendering the log record too big and thus truncated => not valid JSON for DataDog to index => We might wanna look into excluding these file fields from the logs to prevent this

_Originally posted by @stanleynguyen in https://github.com/opengovsg/postmangovsg/pull/1768#discussion_r980814546_

**Comment by jhibberd-gov** [comment]
Moved to Notion.
