### ISSUE TITLE
Persistent Error message: "mimeType" is not allowed to be empty when uploading the file

### ISSUE THREAD

**Issue by pettypychen** [opengovsg/postmangovsg#185]
**Problem**
Chrome/Windows
When user tried to upload a csv (comma, delimited) file on step 2 of the SMS campaign. It generated an error `"mimeType" is not allowed to be empty when uploading the file`. She was able to upload the same file using an iPad on safari.

She took a screenshot of the console:
![eeeb639e-d8cb-452e-be84-04a65be06802 2](https://user-images.githubusercontent.com/39106042/80687971-ace0e400-8afd-11ea-9769-0cce5fa4c926.JPG)

![d508f46e-a36b-426f-976c-df0d7a6d7aaa 2](https://user-images.githubusercontent.com/39106042/80687975-b0746b00-8afd-11ea-8ae8-c57e3434dd1d.JPG)

**Not able to replicate the problem**
I tried using her csv file on Chrome/Mac and VM Chrome/Windows and was not able to replicate the error.

**Comment by jeantanzj** [comment]
We got a second report on this, can reprioritise? @pettypychen 

Could we set a fallback mimetype? @chinying

**Comment by pettypychen** [comment]
@jeantanzj yes we should prioritise this bug for fixing. I have ~4 reports since the first report. Another person just reported it this morning (Microsoft Edge browser). Can we discuss who should take this task during sync-up?

**Comment by jeantanzj** [comment]
I can repro, will look into this
