### ISSUE TITLE
Fix function signatures to remove unnecessary `void`

### ISSUE THREAD

**Issue by tan-zx** [opengovsg/postmangovsg#1894]
this should be `null` instead of `void` (see https://www.tutorialsteacher.com/typescript/typescript-void)

actually, when will `mail` not be falsy? there should always be a mail sent? so the nested`if (mail)` statement can be removed?

_Originally posted by @tan-zx in https://github.com/opengovsg/postmangovsg/pull/1884#discussion_r1055169626_

**Comment by tan-zx** [comment]
this too https://github.com/opengovsg/postmangovsg/pull/1884#discussion_r1055179325

**Comment by jhibberd-gov** [comment]
Moved to Notion.
