### ISSUE TITLE
Remove unnecessary logger.info across entire codebase

### ISSUE THREAD

**Issue by tan-zx** [opengovsg/postmangovsg#1902]
- we alr have trace id (on DataDog), so we can correlate logs across different functions, so we don't need to log message in detail
- no point logging these happy paths `logger.info` across the entire codebase

_Originally posted by @tan-zx in https://github.com/opengovsg/postmangovsg/pull/1888#discussion_r1060432331_

**Comment by jhibberd-gov** [comment]
Moved to Notion.
