### ISSUE TITLE
What license is this on?

### ISSUE THREAD

**Issue by harishpillay** [opengovsg/postmangovsg#1931]
I can't seem to find the license statement for this repo. Is it on GPLv3?

**Comment by stanleynguyen** [comment]
We're currently on [MIT license](https://github.com/opengovsg/postmangovsg/blob/master/docs/LICENSE.md). Will move it to root so it show up on Github. Thanks for the notice @harishpillay

**Comment by jhibberd-gov** [comment]
Moved to Notion.
