### ISSUE TITLE
Feature: Show errors once the user uploads an excel file

### ISSUE THREAD

**Issue by pettypychen** [opengovsg/postmangovsg#194]
**Case with no error:** No error message is shown. Proceed to send test message as per UX flow. 

**Cases with error messages:**
1. Header included in the template message is not found in the csv file
`The attribute you included in the template is not found in the csv header. Consider checking your template or the csv file.`
**Ideal user flow:** Prevents the user to proceed to the next step because the message is probably going to be incomplete. 

2. Empty cells
`The attribute you included in the template had an empty cell in cell _____.`
**Ideal user flow**: Allows the user to override and proceed to send campaign because not every cell must have content. It is context-dependent. 

3. Wrong file type [done]

**Comment by jeantanzj** [comment]
Reopened to consider showing list of invalid emails

**Comment by lshaowei18** [comment]
Have we done this yet?

**Comment by pettypychen** [comment]
I decided to close this for now because it is a non-goal to address the invalid email within Postman's features given the high false positive. I have updated the [guide](https://guide.postman.gov.sg/guide/quick-start/email/halting-of-email-campaigns#recurrent-halting-of-campaigns) to recommend debounce.io's service if people are interested in cleaning up their mailing list.
