### ISSUE TITLE
Feature: Verification of credentials after creation

### ISSUE THREAD

**Issue by pettypychen** [opengovsg/postmangovsg#221]
**Baseline:** Right now you cannot see the credential once you saved it. 

**Ideal user flow:** Preview credentials.

**Comment by jeantanzj** [comment]
Send a test message from the saved credential in Settings

**Comment by lamkeewei** [comment]
Any preferred UI design for this? Otherwise, my thoughts are to retrieve the credentials and show it in a modal with similar styles to the "Add credentials" modal.

**Comment by jeantanzj** [comment]
As mentioned during the sync up - credentials are not shown to the user. 
A modal opens and they get to send a message to themselves.
