### ISSUE TITLE
Default send rate to 30? for email campaigns

### ISSUE THREAD

**Issue by jeantanzj** [opengovsg/postmangovsg#258]
<img width="355" alt="Screenshot 2020-05-18 at 5 38 54 PM" src="https://user-images.githubusercontent.com/33819199/82198126-734a0e80-992e-11ea-8c98-bc49df8039e2.png">

We default the email credential for a project to EMAIL_DEFAULT. This means only 1 email campaign can be in progress at a time. 

Our ses account limit is 40/s

This can be remediated in various ways:
- Default send rate to 30 so the one campaign that is in progress finishes as fast as it can
- Do something about the default credential, so that multiple email campaigns can be in progress simultaneously, yet not exceed 40/s. I haven't thought about it yet

**Comment by pettypychen** [comment]
Not relevant anymore. Closing the issue.
