### ISSUE TITLE
Set up local storage option for uploading files

### ISSUE THREAD

**Issue by jeantanzj** [opengovsg/postmangovsg#284]
**Is your feature request related to a problem? Please describe.**

No alternative to S3 currently exists for local development. We cannot test POST /template without an S3 bucket. 

**Describe the solution you'd like**
Set up local storage option for uploading files. Chinying suggested minio

**Comment by LoneRifle** [comment]
I've done some homework, and think that @localstack might be a great drop-in replacement to AWS for local development purposes. The only tweaks we would need to do to the codebase would be to allow the insertion of the `endpoint` into relevant points in the codebase (notably where `awsRegion` comes up).

Note that localstack does not expose ECS APIs
