### ISSUE TITLE
Download list of invalid recipients for sms

### ISSUE THREAD

**Issue by jeantanzj** [opengovsg/postmangovsg#302]
**Is your feature request related to a problem? Please describe.**
Users want to see the state of their sms messages.

**Describe the solution you'd like**
After #211 is released, we can create a read replica and an endpoint that can pull the error_code / received_at / updated_at for the campaign's messages,  returning these as a csv. 
But there's a replication lag so we have to set expectations right.

**Comment by lshaowei18** [comment]
What are the implications of reading from the same database instead of creating a read replica? Sorry didn't quite understood it when you were explaining during sync up.

**Comment by pettypychen** [comment]
This is to prevent the DB being hit too many times which would result in performance issue. The issue with the read replica is that you might have the 2 DB not in sync. This is the reason why Azima needs to check how long it takes to replicate DB as it impacts the user experience. If the csv can only be generated in a few hours then we would need to tell the users that errors are not instantaneous to set the expectation.
