### ISSUE TITLE
Registered mail

### ISSUE THREAD

**Issue by jeantanzj** [opengovsg/postmangovsg#304]
**Is your feature request related to a problem? Please describe.**
Two problems to solve here

1. Can we ensure that the person reading the message is the intended recipient?
   -  Intended recipient means: 
a) they own the number, and/or 
b) they are the actual person who should be receiving the information. 
The first constraint may allow recycled numbers. 
The second constraint is tighter, and requires the recipient to verify themselves in some manner.
2. Can we ensure that an unintended recipient who receives the message cannot read the message? 

**Describe the solution you'd like**
We can achieve 2) by locking the message behind a password.
We can achieve a) by sending an otp to the recipient on file  -- this would be the password.
We may achieve b) by making the password something that *only the recipient would know without having the password sent to them*. An example might be the recipient's birth date, or last 4 digits of nric. 
If we attempt to achieve b), a possible flow would be:

1. admin creates a campaign that supports registered mail (possibly in template.model)
2. admin specifies a password column (possibly in campaigns.model)
3. a link is generated for each recipient 
4. the link is sent to the recipient
5. when the recipient receives the link, they have to enter their password
6. the correct password unlocks the message.

Possible questions:
- The message could be encrypted to protect against unintentional leaks. Is there a point though? This would be best implemented e2e.
- What if we redacted/deleted messages? The recipient only has the link, but the message would be missing. 

This problem is fairly complex, and requires re-wiring / new tables to support sending links instead of templated messages. The generated link also needs an unlock mechanism which then retrieves templated message / decrypts an encrypted message

**Comment by lshaowei18** [comment]
In digital MC, are the MCs encrypted?

**Comment by lshaowei18** [comment]
Preventing recycled numbers can be tough and I am not sure if it is worth the effort. I guess it is also worth considering allowing users to choose what kind of password they want, ie OTP or password.

**Comment by pettypychen** [comment]
New tasks/issues generated.

Rename feature to `locked email`.
