### ISSUE TITLE
Consider getting rid of the SENT and ENQUEUED state.

### ISSUE THREAD

**Issue by jeantanzj** [opengovsg/postmangovsg#319]
The ENQUEUE state was initially meant to support an enqueue worker, but given that we do not seem to be heading down this route, there's no point in keeping it.

The SENT state was meant for the logger to determine if it could log the job. This would be useful if we had many workers sending simultaneously (so we do not need to scan the job_queue table with many jobs in SENDING state). But given that we only have 2 workers sending at a time, we can determine if a logger should log a job using the SENDING state.

**Comment by pettypychen** [comment]
I was wondering if it makes sense to dedicate a few days a month closing housekeeping related issues before we push features. This would help keep things in order before we make new changes.
