### ISSUE TITLE
Better sending stats

### ISSUE THREAD

**Issue by pregnantboy** [opengovsg/postmangovsg#336]
**Is your feature request related to a problem? Please describe.**
The current sending stats do not take into the account statuses from callbacks. i.e. messages with errors from callbacks still make up the `sent` count.

**Describe the solution you'd like**
There should be an extra count (e.g. `sending`) for messages in transit (i.e. not delivered yet). And `sent` count should include messages that has successfully reached the recipient. `errored` count should include messages with immediate and downstream errors.

**Comment by pettypychen** [comment]
Error code proposed changes [here](https://docs.google.com/spreadsheets/d/1z2hHa8uSuw1SVbgG29bfx3hCBQabRhLZ8o3nF1Jzwqk/edit?usp=sharing).

**Comment by lamkeewei** [comment]
@pettypychen I think the original issue that Ian raised was with regards to adding an intermediate state (e.g. `sending`) to represent messages that have been sent but their statuses are not yet finalised by the callback.  

Quick check, is the priority here to clean up the error messages or to add this new intermediate state?

**Comment by lamkeewei** [comment]
As discussed, external service (Twilio, Telegram) client errors will be preserved for easier debugging. However, these will be remapped in the exported CSV. Postman API errors will be updated.
