### ISSUE TITLE
[Telegram] [Backend] Telegram settings 

### ISSUE THREAD

**Issue by jeantanzj** [opengovsg/postmangovsg#341]
POST /settings/credentials 
- should store bot id and bot token, where bot id is the name of the secret
- change credential logic - create secret if it doesn’t exist, else update the secret. Rationale being that the bot token can be revoked and regenerated
- validate bot token using Telegram’s /getMe

DELETE /settings/credentials
- should delete credential

**Comment by lamkeewei** [comment]
Quick note on this. After validation of the token with /getMe, there will be two additional steps:
1. Registration of the default webhook url for the associated bot.
2. Registration of custom Telegram commands for the bot (e.g. /updatenumber). _Pending discussion/confirmation._
