### ISSUE TITLE
[Telegram][Backend] Create template

### ISSUE THREAD

**Issue by jeantanzj** [opengovsg/postmangovsg#342]
PUT /campaigns/:id/telegram/template
- Create template as in SMS, using the core Templateclient
- Check telegram for what html tags we can support, if any. Configure xss options
- Check new line parsing (SMS uses \n, Email uses `<br>`. What does telegram use?)

Not sure if we want to extract out templating at this point to support registered mail as well. Probably should be another story. Evaluate the effort needed and coordinate with whomever is working on the equivalent part of registered mail (#363)

**Comment by lamkeewei** [comment]
Will coordinate with @lshaowei18 on this. In the meantime I will just put in the scaffold for this feature.
