### ISSUE TITLE
[Telegram] [Backend] Test credentials

### ISSUE THREAD

**Issue by jeantanzj** [opengovsg/postmangovsg#344]
POST /campaigns/:id/telegram/credentials
- Associate existing user Telegram credentials to the campaign

POST /campaigns/:id/telegram/new-credentials
- Create new Telegram credentials and associate with the campaign

POST /settings/telegram/credentials/verify or /test or equivalent
- Choose the bot ID to send a test message (as above)

**Comment by lamkeewei** [comment]
As discussed during sync-up, we will allow for new Telegram credentials to be added during campaign creation to provide a more consistent UX.

Our previous rationale for not allowing new credentials were as follow:
1. The Telegram handler starts listening for messages the moment a new token is added. We did not want the handler to be listening for messages from potentially inactive bots. 
2. We wanted to make it explicit through the user flow that the users have to first create the Telegram bot and get their intended recipients to sign up first before sending out a campaign.  

After re-evaluating, team agrees that point 1 is a minor issue as we are not long-polling for new messages. For point 2, we will provide prompts through the UI to inform the user.
