### ISSUE TITLE
Stats tooltip 

### ISSUE THREAD

**Issue by jeantanzj** [opengovsg/postmangovsg#355]
**Is your feature request related to a problem? Please describe.**
Users do not understand what the stats mean

**Describe the solution you'd like**
Tooltips or some form of explanation on the stats page that errors currently refer to immediate errors.

With the implementation of callback statuses, this may change.

**Comment by pettypychen** [comment]
Users have a hard time figuring out the actions required for the stats page. A possible alternative is to include a simple phrase but the UI is getting progressively cluttered as we add more instructions. A tooltip could solve this pain point. 

The specific feedback was 

> Not sure what the export button is meant to do. I only found out that it is a list of bounced email after I downloaded it

**Comment by jeantanzj** [comment]
Closed as stats tooltip was completed.
Moved Petty's comment to issue #482
