### ISSUE TITLE
[Registered] Shard out templating logic

### ISSUE THREAD

**Issue by pregnantboy** [opengovsg/postmangovsg#363]
- Move templating logic into it's own local node module for better consistency
- Frontend, backend and workers would npm install this module

**Comment by lshaowei18** [comment]
Initially I thought we could just move the whole `TemplateClient` into an npm module, but `TemplateClient` contains `testHydration`, which handles accessing s3, downloading files etc which is out of the scope for the npm module. I'm not sure how we could refactor `testHydration` yet though.

**Comment by lshaowei18** [comment]
`EmailTemplateService.client.testHydration` This code smells but i'm not sure why; it reminds me of [Law of Demeter](https://www.reddit.com/r/programming/comments/4oprd0/the_law_of_demeter_writing_shy_code/) but it doesn't quite fit.
