### ISSUE TITLE
[Registered] New UploadRecipients Component for registered mail

### ISSUE THREAD

**Issue by pregnantboy** [opengovsg/postmangovsg#365]
Additional features for component
- New textarea for `content template`
- Preview first templated unencrypted content
- Uploads file and call new endpoint `email/upload/complete/registered` endpoint

Pending UI design

**Comment by lshaowei18** [comment]
Hmmm I might have missed this out, but how are we going to store the content template? Would it be in email_template table or?

**Comment by miazima** [comment]
@lshaowei18  The content template itself will not be stored, the hydrated message would be encrypted and stored in the new `encrypted_messages` table
