### ISSUE TITLE
Twilio error to be reflected on the sending page

### ISSUE THREAD

**Issue by pettypychen** [opengovsg/postmangovsg#387]
**Is your feature request related to a problem? Please describe.**
MOH user reported Twilio network down time at 10PM on 05/06/2020. Network downtime threw multiple HTTP retrieval failure errors on Twilio console. User unable to tell that there was a Twilio issue on Postman. 

**Other relevant details:**
- Twilio has its own status page to indicate service availability: https://status.twilio.com/. 
- Progress bar on Postman's sending page did not move when Twilio's SMS service was down.

**Describe the solution you'd like**
We are storing callbacks already for the downloadable list of errors so we should have the list of Twilio [error code](https://www.twilio.com/docs/api/errors) in our DB, but displaying multiple errors on Postman is poor UX and can be confusing for users who are not familiar with Twilio `error codes`. 

**Possible solution:** 
We can to display a toast component on the sending page if the progress bar does not move after 5 minutes to explain what is happening and redirect the users to (1) check their Twilio console to review the errors thrown, (2) check Twilio service status on https://status.twilio.com/ for more information, and (3) submit a bug report to Postman .

**Comment by jeantanzj** [comment]
If Twilio has downtime, the progress bar still moves because the messages being sent will return timeout errors.
