### ISSUE TITLE
Add precommit check to prevent secrets from being committed

### ISSUE THREAD

**Issue by jeantanzj** [opengovsg/postmangovsg#393]
**Is your feature request related to a problem? Please describe.**
Intern accidentally committed credentials to forms and go. We could add a precommit check. 

**Describe the solution you'd like**
Consider https://github.com/awslabs/git-secrets

**Comment by xming13** [comment]
For reference:
https://github.com/opengovsg/GoGovSG/blob/develop/package.json#L172
https://github.com/opengovsg/GoGovSG/blob/develop/secrets-check.sh

**Comment by jeantanzj** [comment]
Go's secrets check appears insufficient as it only checks for AWS secret keys, but we also need to protect database URIs, twilio credentials, email credentials. I would prefer to use something that can be extended easily, like [git secrets](https://github.com/awslabs/git-secrets) or [detect-secrets](https://github.com/Yelp/detect-secrets), but the downside is that these tools have to be installed separately.
