### ISSUE TITLE
Alarm and statistics for email bounce rate

### ISSUE THREAD

**Issue by lshaowei18** [opengovsg/postmangovsg#416]
**Is your feature request related to a problem? Please describe.**
Last week's SES pause was unexpected and while we were notified immediately, the message from AWS was rather cryptic and hard to tell that it is super important.

**Describe the solution you'd like**
Could be an alarm on slack whenever the email bounce rate is too high or SES decides to pause the account.

**Describe alternatives you've considered**
Would be the best if we have an automatic failover to another region or another provider, but not sure if that will be hard.

**Comment by lamkeewei** [comment]
Proposing to do the following:
- Setup CloudWatch alerts for Bounce Rates and Complaint Rates ([link](https://docs.aws.amazon.com/ses/latest/DeveloperGuide/reputationdashboard-cloudwatch-alarm.html))
- Either reuse our existing AWS SNS topic or create a new one just for SES alerts
- Link up with Slack using the [Email App](https://slack.com/apps/A0F81496D-email), similar to how existing "Postman AWS Alerts" is configured.

**Comment by jeantanzj** [comment]
Done
