### ISSUE TITLE
Halted message does not go away after the campaign has been restarted by Postman Team

### ISSUE THREAD

**Issue by pettypychen** [opengovsg/postmangovsg#461]
**Describe the bug**
Campaign gets halted if there are more than 20 invalid emails. User sees that the campaign status as `Halted Too many of your emails bounced. Contact us for details. ` Even after the Postman team manually restarts the campaign, the `Halted` status remains on the campaign stats page and the campaign table. 

**Expected behavior**
`Halted` status should change to Sent status when the entire campaign is completed.

**Screenshots**
![Screenshot 2020-07-01 at 1 24 30 PM](https://user-images.githubusercontent.com/39106042/86207975-3b2b2200-bba2-11ea-841c-7b393ee0fa9b.png)

![Screenshot 2020-07-01 at 1 50 57 PM](https://user-images.githubusercontent.com/39106042/86208046-5bf37780-bba2-11ea-8124-64282b5cd731.png)

**Comment by jeantanzj** [comment]
Not an issue. Their campaign got halted near the end, but finished anyway.
