### ISSUE TITLE
Improve messaging in Step 2 (Upload recipients)

### ISSUE THREAD

**Issue by sarahsalim** [opengovsg/postmangovsg#497]
User doesn't know he has to exclude +65 in his CSV file. He sent out a campaign and had to pause when he got errors.

**Tweak message to:**
Only CSV format files are allowed. If you have an Excel file, please convert it by going to File > Save As > CSV (Comma delimited).

CSV file must include a recipient column with recipients' mobile numbers (exclude +65).

<img width="1462" alt="Screenshot 2020-07-07 at 18 21 54" src="https://user-images.githubusercontent.com/27407507/86770723-b5b4df80-c083-11ea-8031-70f2e8ca9f17.png">

**Comment by xming13** [comment]
It would be great if the system can handle mobile numbers with or without +65. 
Is there a particular reason that prevents this from happening?

**Comment by xming13** [comment]
Based on https://github.com/opengovsg/postmangovsg/pull/486#pullrequestreview-442921186, the system is able to handle mobile numbers with or without +65 once it is implemented.

**Comment by pettypychen** [comment]
Tested the fix. Adding +65 or excluding +65 will allow the user to send the SMS. 

Opening a new issue for numbers that included the 65 but not the plus, which would generate an error because Twilio would not be able to recognize the number for SMS sending.

**Comment by lamkeewei** [comment]
This has been resolved by #611. Right now it will work with/without '+65' as well as with just '65'.
