### ISSUE TITLE
Improve copy at Step 4 side bar

### ISSUE THREAD

**Issue by sarahsalim** [opengovsg/postmangovsg#500]
Users commented **Step 4: Send** at side bar is not intuitive as well.

Users suggest 'Preview & Send' as it feels less scary to go to the next step. Like they can preview one more time and make sure their message and CSV file are all correct before they hit 'Send campaign now'.

**Comment by sarahsalim** [comment]
Sorry @miazima I was not clear on the text formatting for the side bar when I opened the issue.
I also want the side bar to be sentence case formatted. 

Step 4 is 'Preview and send' and Step 1 is 'Create message' instead of template.

<img width="401" alt="Screenshot 2020-07-24 at 21 19 58" src="https://user-images.githubusercontent.com/27407507/88395313-71e80700-cdf3-11ea-881d-02567a9cdc25.png">

**Comment by miazima** [comment]
This change was included in #585
