### ISSUE TITLE
Investigate slow sms rates

### ISSUE THREAD

**Issue by jeantanzj** [opengovsg/postmangovsg#501]
**Describe the bug**
A campaign that was supposed to take 140 seconds took 15 minutes. Campaigns to investigate:  3330, 3329

**Additional context**
Not sure if it's because of the ` await Promise.all(messages.map((m) => sendMessage(m)))` in message-worker, which would block on network calls, or because of database contention

**Comment by jeantanzj** [comment]
Update: I think we were bottlenecking on CPU utilization. Just increased the CPU available. Will observe

**Comment by jeantanzj** [comment]
After increasing CPU available, the time taken went down on average (time taken / expected time decreased from ~6 to ~1-2). But there are some campaigns that seem to take a long time. See campaigns 3848 and 3782

**Comment by jeantanzj** [comment]
I wanted to replace `await Promise.all(messages.map((m) => sendMessage(m)))` with Bluebird's concurrency option, eg.
```
manyMessages = // get more messages than the current rate
sendMessageV2 = async (message) => {
const start = Date.now()
await sendMessage(message)
await waitForMs(Date.now() -start)
}
Promise.map(manyMessages.map(sendMessageV2), {concurrency: rate})
```
but you have to determine how many messages to get at once. We risk OOM, and if the worker dies midsend, we may have to resend more duplicates.

**Comment by pettypychen** [comment]
Can I close this one? I thought we fixed it.
