### ISSUE TITLE
Href gets sanitized when the link is a keyword

### ISSUE THREAD

**Issue by lshaowei18** [opengovsg/postmangovsg#516]
**Describe the bug**

In the email template, when you have the href as a keyword like `<a href="{{protectedlink}}">link</a>`, it gets sanitised into `<a href>link</a>`.

**To Reproduce**
![recording](https://user-images.githubusercontent.com/33112945/87287225-6ca1d700-c52c-11ea-8cf5-4222950e829c.gif)

**Expected behavior**
Should retain the keyword. This affects registered mail.

**Comment by lamkeewei** [comment]
Not sure if it's helpful but we also faced a similar issue when we were working on Telegram. `xss-js` was sanitising `tg://...` links values too. We overrode `safeAttrValue` to solve this. Can reference #467 and [here](https://github.com/leizongmin/js-xss#customize-escaping-function-for-value-of-attributes).

**Comment by lshaowei18** [comment]
Nice, thanks! Just tried it out and it works :)

**Comment by lshaowei18** [comment]
Done through #551
