### ISSUE TITLE
[Registered] When user is logged in, registered mail wont display.

### ISSUE THREAD

**Issue by jeantanzj** [opengovsg/postmangovsg#531]
**Describe the bug**
When user is logged in, registered mail wont display.

**To Reproduce**
Same url, when logged out
<img width="1439" alt="Screenshot 2020-07-14 at 2 10 47 PM" src="https://user-images.githubusercontent.com/33819199/87390675-eba21880-c5db-11ea-8fb1-4f1b5412134e.png">
When logged in
<img width="1120" alt="Screenshot 2020-07-14 at 2 10 40 PM" src="https://user-images.githubusercontent.com/33819199/87390687-efce3600-c5db-11ea-99c9-a7c53d9f82d3.png">

**Comment by miazima** [comment]
Closing this issue, as this feature is still under development and the url to access the protected message had been changed after the test email was sent.
