### ISSUE TITLE
Loading of campaign list is slow

### ISSUE THREAD

**Issue by pregnantboy** [opengovsg/postmangovsg#535]
**Describe the bug**
Loading each page of campaigns is slow

for loop is awaiting each promise in series
https://github.com/opengovsg/postmangovsg/blob/20d58642ecdf4cbcf1f4a98df427155e25e56bb9/frontend/src/components/dashboard/campaigns/Campaigns.tsx#L60-L63

**Suggestion**
Return hasFailedRecipient property in same api call that fetches campaign list

**Screenshots**
![Screenshot 2020-07-14 at 5 55 37 PM](https://user-images.githubusercontent.com/10072985/87413693-384a1b80-c5fd-11ea-92ba-d8617bdfff10.png)

**Comment by miazima** [comment]
Resolved in #585
