### ISSUE TITLE
Registered mail Message A input placeholder shows {{recipient}}

### ISSUE THREAD

**Issue by lamkeewei** [opengovsg/postmangovsg#555]
**Describe the bug**
Potentially confusing for the users as the empty placeholder for Message A template includes `Dear {{recipient}}...` but Message A does not support other keywords apart from `{{protectedlink}}`. 

![image](https://user-images.githubusercontent.com/3666479/87529600-d0a9d400-c6c1-11ea-84d7-a54e2bd3bae4.png)
___

![image](https://user-images.githubusercontent.com/3666479/87529281-58431300-c6c1-11ea-88ad-803e07eeaad8.png)

**Comment by jeantanzj** [comment]
Nonissue, fixed by #537
