### ISSUE TITLE
[Unsubscribe] Cron job to send weekly unsubscribe digest to users

### ISSUE THREAD

**Issue by lamkeewei** [opengovsg/postmangovsg#580]
- Sweep `unsubscribe` table for `sent_at = NULL`, send users with at least one message a digest of unsub requests (recipient emails), grouped by campaign
	- Once complete, update `sent_at` 
- Use read replica when generating report

**Open questions**
- How should we execute the cron jobs? 
	- AWS Lambda: Potential for a timeout due to max 15 minutes execution time	
	- Elastic Beanstalk Worker: Each deploy will affect in progress jobs
	- ECS Scheduled Tasks: *To be evaluated*
	- AWS Batch: *To be evaluated*

**Comment by jeantanzj** [comment]
I believe a lambda is sufficient. I ran a daily cron job for digimc to send smses. It never exceeded 15minutes even at 2m rows.

**Comment by lamkeewei** [comment]
Ok. We will implement this using a lambda.
