### ISSUE TITLE
Allow users to view/copy template from sent campaigns

### ISSUE THREAD

**Issue by lshaowei18** [opengovsg/postmangovsg#613]
**Is your feature request related to a problem? Please describe.**
Users want to be able to reuse a template to send it to a different contact list.

**Describe the solution you'd like**
Currently, when a campaign is sent, the user can only see the statistic dashboard: 
<img width="1680" alt="Screenshot 2020-07-27 at 4 16 23 PM" src="https://user-images.githubusercontent.com/33112945/88519333-8828d980-d024-11ea-93fd-0814c7fe91c5.png">

The goal is to display the template that is used in the sent campaigns.

There are several ways to do this:

- We could add the side bar navigation back and include `Step 1 Create message`.
- Display the template on the page, either below the statistics or anywhere that is appropriate.

Do note that in any case, once the campaign is sent, the user should not be able to edit the template.

**Describe alternatives you've considered**
I have considered having saved templates that are tied to users, so that when a user wants to create a campaign she can just select from a dropdown which of the shared template she wants to use for the campaign.

However, the effort to do this is quite high compared to the value that it brings to the user. We will have to a page for them to create, edit, delete templates and there are afew edge cases to be mindful of.

**Additional context**
This came from a conversation between @jeantanzj, @pettypychen and @lshaowei18, where the initial goal was to evaluate if we should work on reusable campaigns(issue #16). More information could be found here: https://docs.google.com/document/d/1Chovlm4pBqqhkXi0CdkF3yACR77fpqYbdhDCjuetzZU/edit

**Comment by lshaowei18** [comment]
Hi @sarahsalim do you have any thoughts on this

**Comment by pettypychen** [comment]
Deprioritise for now because designers are working on trial mode

**Comment by pettypychen** [comment]
Duplication button released

**Comment by pettypychen** [comment]
Duplication button released
