### ISSUE TITLE
Export Error Spinner keeps spinning unless you you refresh the page

### ISSUE THREAD

**Issue by pettypychen** [opengovsg/postmangovsg#623]
**Describe the bug**
On the campaign stats page, the `export error spinner` will keep spinning unless you refresh the page again. 

**To Reproduce**
1. Send a normal campaign with an invalid recipient
2. Keep the campaign stats page open for report generation export button
3. No export button. The spinner will keep spinning. 

**Expected behavior**
The report export button should show up after the spinner is done spinning to let the user know that the report is ready for export.

**Comment by jeantanzj** [comment]
Spinner will spin when refresh_stats is called since statistics' updated_at is updated.
