### ISSUE TITLE
Protected mail gets cut off when converted to PDF in some browsers

### ISSUE THREAD

**Issue by lshaowei18** [opengovsg/postmangovsg#629]
**Describe the bug**
<img width="1680" alt="Screenshot 2020-07-29 at 5 52 12 PM" src="https://user-images.githubusercontent.com/33112945/88785831-48005d00-d1c4-11ea-89b9-e05101bd97d2.png">

PDF printed from Chrome on Samsung S7. 

**To Reproduce**

1. Create a password protected mail, with template B's content more than 1 page long.
2. Use a mobile phone to visit the protected link
3. Unlock the content with the password 
4. Save the page as PDF

**Expected behavior**
The text shouldn't be cut off.

<img width="922" alt="Screenshot 2020-07-29 at 5 55 32 PM" src="https://user-images.githubusercontent.com/33112945/88786145-b8a77980-d1c4-11ea-9d7b-7952754d94d0.png">

**Comment by lshaowei18** [comment]
Jean suggested `wrap @media screen {}  around existing css` and Kee Wei suggested `Workaround can be to wrap all sections of text in <p> and set break-inside: avoid.`

**Comment by pettypychen** [comment]
closing the issue for now given this is not a priority.
