### ISSUE TITLE
Better user experience for creation of template

### ISSUE THREAD

**Issue by lshaowei18** [opengovsg/postmangovsg#641]
**Is your feature request related to a problem? Please describe.**
Sometimes when testing, I forget what the columns in my csv file looks like, and I find myself referring to the csv file to check the columns.

My csv files are small and has few columns, so I imagine for users who work with huge csv files it must be quite troublesome.

**Describe the solution you'd like**
I think uploading the file should come first or the same step as creating the template. This will allow us to show the users what their csv headers looks like, or we could also do something more complex like:
![recording (13)](https://user-images.githubusercontent.com/33112945/90354787-e0c82100-e07c-11ea-8a74-65c439d1df42.gif)

**Comment by pettypychen** [comment]
UX research completed. New flow would impact the new users more than experienced users. Given that the priority is user acquisition, we will stick with the current uxer flow for now.
