### ISSUE TITLE
Document/replace local node module, postman-templating

### ISSUE THREAD

**Issue by lshaowei18** [opengovsg/postmangovsg#645]
**Is your feature request related to a problem? Please describe.**
Working with the local node module, postman-templating, is an anti pattern and it is quite hard to find information on how to make changes to it.

Struggled for few hours to debug deployment to staging.

**Describe the solution you'd like**
Clear guide on how to update, install dependencies. IE: Needs to delete package-lock.json in parent module in order for it to install the correct node modules on postman-templating.

**Describe alternatives you've considered**
Move the local node module into a separate github repo and npm install from there, but it comes with a different set of problems and challenges.

**Comment by xming13** [comment]
Related: https://github.com/opengovsg/postmangovsg/issues/394
