### ISSUE TITLE
Park IMDA's campaign in Production

### ISSUE THREAD

**Issue by jeantanzj** [opengovsg/postmangovsg#646]
Move IMDA's 289k data to production
- [ ] Find the ids of IMDA campaigns that were sent on staging
- [ ] Create 1 campaign on prod 
- [ ] Create 1 statistic on prod
- [ ] Get email messages for those campaign ids. Change the campaign id of those email messages to the one created in step 2. 
- [ ] Take a snapshot of prod
- [ ] Insert those email messages into prod, without id. 
- [ ] Update the stats

**Comment by pettypychen** [comment]
P1 after custom domain launch

**Comment by jeantanzj** [comment]
Parked stats, job_queue, campaigns, email_templates. Did not move the messages
