### ISSUE TITLE
Evaluate PBKDF2 with 10k iterations for password-protected feature

### ISSUE THREAD

**Issue by pettypychen** [opengovsg/postmangovsg#650]
GEN risk assessment suggested conducting a performance test for PBKDF2 with 10k iterations. 

[NIS 2020 recommendation](https://pages.nist.gov/800-63-3/sp800-63b.html#sec5): `For PBKDF2, the cost factor is an iteration count: the more times the PBKDF2 function is iterated, the longer it takes to compute the password hash. Therefore, the iteration count SHOULD be as large as verification server performance will allow, typically at least 10,000 iterations.`

**Comment by jeantanzj** [comment]
I think we can actually close this, because we rate limit the verification endpoint. It can't be bruteforced easily
