### ISSUE TITLE
Attachments for email messages

### ISSUE THREAD

**Issue by jeantanzj** [opengovsg/postmangovsg#656]
**Is your feature request related to a problem? Please describe.**
Some users want to be able to attach files, instead of hosting them on Go. It's understandable because links don't work on the intranet

**Describe the solution you'd like**
A rough solution might be:
- Upload an attachment to s3, and validate the size (this could be done pre-upload on client side). 
- Save an array of s3 keys - because they're likely to ask for multiple attachments - to the email_template table. 
- On server side, get the s3 file's metadata to check that the size is indeed what the client claimed, and validate the file extension as well.
- When worker picks up the email job, retrieve these attachments, and hold them in memory, passing them off to the mail client until all the messages are sent.

**Comment by pettypychen** [comment]
Frequently asked feature because secrets GSIB cannot see go.gov.sg links. Consider implementing this to capture more use cases.

**Comment by stanleynguyen** [comment]
New context: go.gov.sg links are supported on intranet now. Currently we're still formulating how this feature's gonna be like and also testing with users on having attachments as go links

**Comment by lisatjide** [comment]
closing this since this is documented on notion
