### ISSUE TITLE
Singapore numbers starting with 802 fail Twilio validation

### ISSUE THREAD

**Issue by lamkeewei** [opengovsg/postmangovsg#672]
**Describe the bug**
SMS messages to Singaporean numbers starting with `802` will result in an error from Twilio's API. I suspect Twilio uses `libphonenumber` for validation on their server side. So while we bypassed our own validation in #636, Twilio's validation still throws a false positive. 

**To Reproduce**
1. Use test Twilio credentials to avoid sending out actual SMS messages
2. Send a validation message to a number starting with `802`
3. Following error will be thrown `Error: The 'To' number +65802XXXXX is not a valid phone number.`

**Possible solution**
Use `forceDelivery` for Singaporean numbers. [Example](https://github.com/opengovsg/FormSG/blob/525c1bb8e042e74adcca429df0f544d97a6c821a/src/app/services/sms.service.ts#L176) from FormSG.

**Comment by jeantanzj** [comment]
wrong reference in 675.
