### ISSUE TITLE
Password protected - incorrect templating error

### ISSUE THREAD

**Issue by jeantanzj** [opengovsg/postmangovsg#695]
<img width="1211" alt="Screenshot 2020-09-07 at 3 16 53 PM" src="https://user-images.githubusercontent.com/33819199/92359122-4d36bd00-f11d-11ea-82ea-8759f33e0ac3.png">

As seen in the screenshot, the error says "protectedlink" doesn't exist, when it does. This occurs when you enter a keyword prepended with a hash, such as in `{{#name}}`

**Comment by miazima** [comment]
I could reproduce this issue on localhost, but upon checking on staging and production, the issue did not appear there. I suspect this has to do with the recent update to the postman-templating module. Running a clean install of postman-templating module resolved the issue on localhost for me.


![image](https://user-images.githubusercontent.com/5744384/92673169-10e9a380-f34d-11ea-9f3c-abd86602382f.png)
![image](https://user-images.githubusercontent.com/5744384/92673272-51e1b800-f34d-11ea-903e-59de66e34544.png)
![image](https://user-images.githubusercontent.com/5744384/92673336-7473d100-f34d-11ea-9bf3-8f72c27b3f75.png)
