### ISSUE TITLE
Transfer of backups from AWS S3 bucket to Google Cloud Storage bucket

### ISSUE THREAD

**Issue by lamkeewei** [opengovsg/postmangovsg#704]
Utilise [Google Cloud Storage Transfer Service](https://cloud.google.com/storage-transfer/docs/create-manage-transfer-console) to regularly copy database backups from S3 generated in #703 to GCS bucket.

**Requirements**
- Setup account for Google Cloud Platform
- Create AWS IAM role with limited read-only permissions for use with Storage Transfer service
- Configure transfer job between S3 and GCS
- Harden network perimeter on GCP. Reference following [guide](https://cloud.google.com/solutions/transferring-data-from-amazon-s3-to-cloud-storage-using-vpc-service-controls-and-storage-transfer-service) from GCP docs.

**Comment by miazima** [comment]
I have set up a Cloud Transfer daily job that transfers files from the dedicated staging rds dump backup s3 bucket to the corresponding cloud storage bucket. This is on our current gsuite account and it is working smoothly thus far. 

Next steps:
Replicate this for staging and production in the new GCP account dedicated for backups (when ready)

**Comment by lamkeewei** [comment]
Closing this as we are no longer using Transfer Service.
