### ISSUE TITLE
Sending emails from custom domains

### ISSUE THREAD

**Issue by lshaowei18** [opengovsg/postmangovsg#714]
**Is your feature request related to a problem? Please describe.**
Users are requesting is the ability to change the ‘from’ in an email to their agency’s email address.

We are currently doing this through a separate environment, which is tedious to maintain.

**Describe the solution you'd like**
Allow users to change the 'from' to the email that they are logged into, if their IT departments have already setup the proper SPF/DKIM records.

We have decided that we will settle the SPF/DKIM records offline & manually for now with the IT departments.

What the user experience will be like:

1. User contacts IT department to liaise with us to setup the SPF/DKIM records. 
2. Once it is done, users should be able to see that there are two options in the `from` dropdown; `donotreply@mail.postman.gov.sg` & the email address that she used to login to postman.

**Additional context**
Discussed extensively [here](https://docs.google.com/document/d/1VoApksmzT-QEgzBZnaRX7XrqxPHrcQMR4fZC-vm8F3k/edit#).

**Comment by lshaowei18** [comment]
## TODO

### Backend


#### Endpoint to verify email domain
Either return eligible "from" addresses or if email domain is verified and can be used
<img width="447" alt="Screenshot 2020-09-15 at 11 25 58 AM" src="https://user-images.githubusercontent.com/33112945/93161946-3eb45b00-f746-11ea-80d4-9b28216cc833.png">

#### Database change
Add a new column called `from` in email_templates, which is used to store the `from` email address for each email campaign. Can't be null, defaults to `donotreply@mail.postman.gov.sg`. Do we have to backfill all the old campaigns?

#### Modify PUT email/template
- Add a new middleware
  - Checks that the `from` email address is either the default or the user’s email address. If it is neither, return 400.
  - If default, return 200.
  - Checks that the user’s email domain is in the db table that stores the verified domain. Return 400 if it is not in the table.
- Modify storeTemplate to store the email address under “from” in email_templates.

**Comment by pettypychen** [comment]
Closing this issue because the feature is launched
