### ISSUE TITLE
Style guide for logging

### ISSUE THREAD

**Issue by lshaowei18** [opengovsg/postmangovsg#729]
**Is your feature request related to a problem? Please describe.**
The logs that we have now are messy, making it harder to troubleshoot.

**Describe the solution you'd like**
Style guide or patterns that the team should follow. It could be: 
- Establishing a format that each line of log should follow and what information it should contain. Eg: `2018-07-29 | 21:10:29.178 |  INFO  | Service started in 3434 ms.`
- Explain the different levels of logging & give relevant examples from the codebase of when & why a level is picked. (Levels referring to Debug, Info, Warning, Error)

**Describe alternatives you've considered**
Thought of formatting it in a way that can be used by dashboards and metrics services like Grafana, still unsure if it's an overkill.

**Additional context**

**Comment by jeantanzj** [comment]
They should be namespaced, perhaps in a meta property (https://www.npmjs.com/package/winston#streams-objectmode--and-info-objects). 

Ideally, we should log in json (https://www.scalyr.com/blog/aws-lambda-logging-best-practices/) and the format might look like 

`{ level: 'info', datetime: '2020-09-23T01:03:00.000Z', namespace: 'serviceNameOrFunctionName',  message: 'some message'}`

winston-cloudwatch formats our json logs into text right now
