### ISSUE TITLE
Fix Google Analytics (CSP)

### ISSUE THREAD

**Issue by lshaowei18** [opengovsg/postmangovsg#742]
**Describe the bug**
<img width="1680" alt="Screenshot 2020-09-28 at 4 51 05 PM" src="https://user-images.githubusercontent.com/33112945/94411158-d08e8000-01aa-11eb-886c-85cf6a330ddc.png">

It seems like GA is still updated though, so I am not sure what issues this is causing.

**Comment by pettypychen** [comment]
The new SIS might have an impact on our Google Analytics given that the requests will be routed through a virtual container and there are only a few dedicated IP that will relay the request.
