### ISSUE TITLE
[Monitoring] Batch jobs / Lambda

### ISSUE THREAD

**Issue by lshaowei18** [opengovsg/postmangovsg#746]
It was suggested in the monitoring guide to setup cronitor.io.

However, I don't think it fits our use case since if i'm not wrong we only have 1 cron job which is the unsubscribe digest. We currently have this cloudwatch alarm: 

Alarm-Unsubscribe-Digest-Error
Metric: Lambda > By Function Name > unsubscribe-digest-production > Errors
Statistics: Sum
Period: 604800 seconds (1 week)
Threshold: Greater than 0
Datapoints to alarm: 1 out of 1

**Comment by chinying** [comment]
Hm I don't think this is that important (ie. not a P1) since we don't have any critical functionality running on scheduled jobs.

The cloudwatch alarm is for monitoring a separate metric though, it's for the presence of errors rather than an "uptime check" that cronitor is supposed to serve.

**Comment by pettypychen** [comment]
Closing this issue because not a priority for now
