### ISSUE TITLE
[Monitoring] Incident Response

### ISSUE THREAD

**Issue by lshaowei18** [opengovsg/postmangovsg#747]
- Understand definition of incident
- Understand roles and responsibilities
- Understand escalation procedure
- Understand no-alcohol rule while on-call
- Understand rollback procedure
- Understand hotfix procedure

I don't think this is documented yet. We can reference formsg's incident response playbook.

**Comment by jeantanzj** [comment]
<img width="759" alt="Screenshot 2020-10-13 at 12 45 27 PM" src="https://user-images.githubusercontent.com/33819199/95816575-05c1d300-0d52-11eb-8b8f-8be58df111be.png">
<img width="795" alt="Screenshot 2020-10-13 at 12 43 33 PM" src="https://user-images.githubusercontent.com/33819199/95816579-08242d00-0d52-11eb-98bb-2ed5b62938e9.png">
