### ISSUE TITLE
[Backup] [Stage 2] Disaster Recovery Plan

### ISSUE THREAD

**Issue by lshaowei18** [opengovsg/postmangovsg#749]
- [x] Create a Disaster Recovery plan document
- [x] Document database configuration
- [x] Document online backup configurations
- [x] Document recovery plan each backup method
- [x] Document failover steps for each backup method
- [x] Define Recovery Time Objective and Recovery Point Objective for each recovery method
- [x] Define steps to verify integrity of restore database
- [x] Define steps to verify application's connection to new database instance

**Comment by lamkeewei** [comment]
First draft of the plan is available [here](https://docs.google.com/document/d/1zOqgctjX_NPDtVJqmEX3sM8-RehpdzGDarQR_PvdBH4/edit#heading=h.v9mffngsj3j5).

**Comment by lamkeewei** [comment]
Added RTO estimates for online backups. Pending completion of offline backups to time RTO.
