### ISSUE TITLE
[Backup] [Stage 3] Offline backups

### ISSUE THREAD

**Issue by lshaowei18** [opengovsg/postmangovsg#750]
- [x] Configure offline backup method
- [x] Restore from offline backup into RDS
- [x] Installing database software on a fresh server
- [x] Configuring database software
- [x] Restore from offline backup to server running database software
- [x] Configure server to receive connections from application servers
- [x] Define how and when to move back to primary database service
- [x] Update Disaster Recovery plan document with offline backup steps and recovery plan

**Comment by lamkeewei** [comment]
Will close this again once I've updated all docs and ran through the setup with pallani.

**Comment by pettypychen** [comment]
Have we gone through this already?

**Comment by pettypychen** [comment]
@lamkeewei are we done with this list?

**Comment by lamkeewei** [comment]
Code changes required are merged in at #851. Just left with updating the docs. Will get to it and then close this. Missed out on this, sorry!

**Comment by lamkeewei** [comment]
Updated Postman Disaster Recovery docs with reference to required docs.
