### ISSUE TITLE
[Custom Domain] Verify that sns topic is hooked correctly for a new from address

### ISSUE THREAD

**Issue by jeantanzj** [opengovsg/postmangovsg#777]
When adding a new from address,
1) add the from address to verified address on ses
2) get IT team to add DNS records
3) make sure the verified address's notifications go to an sns topic that calls the callback endpoints, with original headers enabled, and email forwarding disabled. 

We've checked for 1) and 2), but I'd missed out on the 3rd check.

**Comment by lamkeewei** [comment]
Use configuration set

**Comment by stanleynguyen** [comment]
Closing it since we're looking to deprecate the custom email sender feature
