### ISSUE TITLE
[Custom Domain] More informative error when display name is modified, & differs from saved template

### ISSUE THREAD

**Issue by jeantanzj** [opengovsg/postmangovsg#778]
If you saved a template with the email address "ABC <noreply@abc.com>", and subsequently, changed the display name such that the valid from address is "XYZ <noreply@abc.com>", the newly modified template would be considered invalid. Although this is expected behavior, the error displayed is "This From Address is not verified", which is incorrect. 

We could mitigate this by:
1) adding a more informative error when template is saved - so that the user will select the correct email from the dropdown
2) displaying the error when a campaign first loads, instead of on next
3) perhaps changing "from" in the template to just the email address instead? we'll retrieve the display name from email_from_addresses

**Comment by pettypychen** [comment]
Can we go with option 3? perhaps changing "from" in the template to just the email address instead? we'll retrieve the display name from email_from_addresses @sarahsalim @NatMaeTan

**Comment by NatMaeTan** [comment]
We've discussed with Kee Wei, and suggest to go with option 3 as discussed.

**Comment by jhibberd-gov** [comment]
Moved to Notion.
