### ISSUE TITLE
Redaction of Params

### ISSUE THREAD

**Issue by pettypychen** [opengovsg/postmangovsg#779]
Data redaction for expired campaign (implementation [doc](https://docs.google.com/document/d/1ZtkevL3Opx88UbnKljdvUmuxPUiz77cuvx4CKcWD-q8/edit)). 

Campaign `param` can be redacted 7 days after a campaign is sent. Only redact the `param` for the initial implementation. No need to inform users yet as the redaction of `params` will not affect campaign stats. Only need to inform users once we decide on redacting the recipient field. 

- [x] @leonardloo @pettypychen Decide whether we should redact the recipient by the end of next week after talking to Vault and align OGP product direction. 
- [x] @jeantanzj to add in comments for the implementation plan

**Comment by lamkeewei** [comment]
Implementation details and decisions documented [here](https://docs.google.com/document/d/1ZtkevL3Opx88UbnKljdvUmuxPUiz77cuvx4CKcWD-q8/edit#heading=h.g33yfiuahplv).

**Comment by lamkeewei** [comment]
Frontend redaction has been rolled out without issues from users. Proceeding to fully redact data from messages table.

**Comment by syan-syan** [comment]
@lamkeewei is this completed?

**Comment by lamkeewei** [comment]
I realised I have yet to implement the full redaction from the database, only the frontend part. Will complete this.
