### ISSUE TITLE
Rich text format

### ISSUE THREAD

**Issue by pettypychen** [opengovsg/postmangovsg#801]
**Is your feature request related to a problem? Please describe.**
Our users are not tech-savvy and have a hard time learning html code for formatting their emails. 

**Describe the solution you'd like**
[Google doc](https://docs.google.com/document/d/1SxuwY3zPbVeu_xM0P0lVt2MbCPqRc4hjz8Zfaxn3Qmk/edit?usp=sharing)

**Comment by lamkeewei** [comment]
Some points to note at sync-up
- If possible, abstract raw HTML away from user
- Allow a fallback to editing raw HTML
- Take note of email safe CSS/HTML
- Ensure that template is escaped to prevent XSS
- Only used for Email/Protected Email campaigns
- Should allow rich text editor on both Message A and Message B for Protected Email campaigns
