### ISSUE TITLE
Trigger slack notifications for successful verification of backups

### ISSUE THREAD

**Issue by miazima** [opengovsg/postmangovsg#804]
**Is your feature request related to a problem? Please describe.**
In the current implementation, there is a slack notification triggered in the event of failure to verify the rds backups in the offline GCP account. it would be useful to extend a similar notification on successful verification too.

**Describe the solution you'd like**
- Create a new logs router sink to trigger a pubsub notification on successful restore
- Setup a cloud function to be triggered on upon a new message being published in the above pubsub topic
- The cloud function will send messages using an incoming webhook url

The message could contain the date of the restored dump, useful metrics such as number of users, campaigns, messages etc from the restored db, for the purpose of a sanity check.

**Comment by jeantanzj** [comment]
As discussed, could use sentry for this.
