### ISSUE TITLE
Demo Campaign - Create demo campaign modal

### ISSUE THREAD

**Issue by NatMaeTan** [opengovsg/postmangovsg#820]
<img width="825" alt="Screenshot 2020-11-05 at 2 40 38 PM" src="https://user-images.githubusercontent.com/63220614/98207494-b8164000-1f76-11eb-8817-285510f0560f.png">

UI fixes
1. Green banner should be 80px height

2. Close icon should be **Midnight green #004A56** - _Current is hard to see_

3. Spacing between Input label ("The demo campaign has been named for you") and input box should be 16px (1rem)

3. Disabled input box should follow
        Text: Slate #64707D 
        Input box background: Alloy #C1C7CD 30%
        Input box border: Slate #64707D 30%
<img width="1428" alt="Screenshot 2020-11-05 at 3 03 33 PM" src="https://user-images.githubusercontent.com/63220614/98208329-142d9400-1f78-11eb-8150-3e3f716b316a.png">

4. Consistent spacing between elements 48px (3rem)

5. Tall button states should follow Tall Outline, option that is "selected" shows pressed state and hence should not show Tall solid hover state. - _(We will supply a prototype to explain this)_
Wrong states:
![Screen Recording 2020-11-05 at 3 10 48 PM](https://user-images.githubusercontent.com/63220614/98209731-6a9bd200-1f7a-11eb-99d6-d221d5281d14.gif)

If you need further explanation, please approach us.

___

Refer to this screen in Figma [here](https://www.figma.com/file/29FkTqWnA4yLKzstnvyY6X/%F0%9F%91%91Design-Master?node-id=4719%3A45843)

**Comment by jeantanzj** [comment]
> Consistent spacing between elements 48px
Dont know which specific part this refers to

**Comment by jeantanzj** [comment]
<img width="823" alt="Screenshot 2020-11-05 at 7 59 08 PM" src="https://user-images.githubusercontent.com/33819199/98238525-718a0b00-1fa1-11eb-80ce-1767beba79bb.png">
if the green bar is 80px high, it will be misaligned with the close button.

Why are the CreateModal and CreateDemoModal not consistent with the other modals? They have a padding of 78px on the left and right, but other modals have a padding of 166px.

**Comment by jeantanzj** [comment]
<img width="776" alt="Screenshot 2020-11-05 at 8 56 53 PM" src="https://user-images.githubusercontent.com/33819199/98243816-72269f80-1fa9-11eb-9053-349ede2e3b81.png">
moved the close button up
