### ISSUE TITLE
Demo campaign - Creation flow

### ISSUE THREAD

**Issue by NatMaeTan** [opengovsg/postmangovsg#821]
###Overall

1. Banner text color should be midnight green #004A56

### Upload recipients

<img width="200" alt="Screenshot 2020-11-05 at 1 00 39 PM" src="https://user-images.githubusercontent.com/63220614/98210676-e2b6c780-1f7b-11eb-9fbc-0e4d0967b6f5.png">

UI fixes
1. Left thin bar should be Bright blue # 2C2CDC

2. Text should be changed to "per demo campaign"
__
Refer to this screen in Figma [here](https://www.figma.com/file/29FkTqWnA4yLKzstnvyY6X/%F0%9F%91%91Design-Master?node-id=4719%3A39547)

### Insert Credentials

UIUX fixes

1. Change demo credential name to **Postman_SMS_Demo** & **Postman_Telegram_Demo**

2. Disable dropdown and "Add new credentials/Input credentials manually"

3. Change both SMS and Telegram notice banner title to "Use demo credentials"

4. Change Telegram description:
        In demo mode, you can use Postman's default Telegram bot to try sending Telegram messages. In a normal campaign, you’d have to set up your own Telegram bot. **_Learn more_**

Make sure that you and your recipients are subscribed to @postmangovsgbot (hyperlinked to https://go.gov.sg/postmangovsgbot) before proceeding. Unsubscribed recipients will not receive your message.

<img width="200" alt="Screenshot 2020-11-05 at 3 40 44 PM" src="https://user-images.githubusercontent.com/63220614/98211623-45f52980-1f7d-11eb-93f9-78acb0f3363b.png">

5. **_Learn more_** text colour should be bright blue # 2C2CDC

6. When clicking the link for the bot, the pressed state is red. Please change the default color to Bright blue #2C2CDC and changed the pressed state according to the design system.
<img width="200" alt="Screenshot 2020-11-05 at 3 42 14 PM" src="https://user-images.githubusercontent.com/63220614/98211772-85bc1100-1f7d-11eb-849c-dc02ddfff52d.png">

7. Telegram button should be "Validate credentials"
<img width="200" alt="Screenshot 2020-11-05 at 3 55 36 PM" src="https://user-images.githubusercontent.com/63220614/98212979-59a18f80-1f7f-11eb-96bb-643034d7d15e.png">

__ 
Refer to this screen in Figma [here](https://www.figma.com/file/29FkTqWnA4yLKzstnvyY6X/%F0%9F%91%91Design-Master?node-id=4719%3A39572)

**Comment by jeantanzj** [comment]
why are the links so inconsistent

**Comment by lamkeewei** [comment]
One more minor issue for the demo mode flow raised by the designers. The demo mode banner should not be shown in the empty dashboard screen since there's already the button to prompt them to "Try demo SMS/Telegram" which will trigger the demo mode. 

![image](https://user-images.githubusercontent.com/3666479/99510046-8a42e980-29c1-11eb-8616-77b06a629fc9.png)
