### ISSUE TITLE
Use Pingdom's Transaction Checks to ensure frontend renders

### ISSUE THREAD

**Issue by lamkeewei** [opengovsg/postmangovsg#826]
Our current Pingdom check does not detect the situation where the frontend failed to render since a `HTTP 200 OK` is returned even though the JS assets failed to load. Perhaps we can explore using Pingdom's [Transaction Checks](https://help.pingdom.com/hc/en-us/articles/203910642-Transaction-Checks) to catch this. 

The check will:
1. Navigate to https://postman.gov.sg
2. Click on "Sign in"
3. Check that the URL is updated to "https://postman.gov.sg/login".

**Comment by lisatjide** [comment]
done
