### ISSUE TITLE
Empty Spacing for Password-protected Page Persists

### ISSUE THREAD

**Issue by pettypychen** [opengovsg/postmangovsg#857]
**Describe the bug**
The checkbox in the password-protected campaign for the removal of empty spaces should remove spacing from empty excel cells when the private content is rendered on the browser. 

Two places where this bug was found:
1. Preview box for Message B
![127174160_214803056902270_8472513590533795042_n](https://user-images.githubusercontent.com/39106042/100180128-7db71780-2f12-11eb-9cfe-b16a5b70c7b2.jpg)

2. Password-protected content after entering the password (see pdf sent in slack)

**To Reproduce**
`<img src="https://file.go.gov.sg/cpf-logo.png" class="center" width="500" /> <b>Staff name:</b> {{name}} <b>Employee Number/NRIC No:</b> {{ee_no}} / {{nric}} </br> <h1>CPF Board Payslip for the Month of {{month}}</h1> <hr> <h2>Earnings for {{month}} {{year}}</h2> <b>{{9001_desc}}</b> {{9001_value}} <b>{{9002_desc}}</b> {{9002_value}} <b>Gross Salary:</b> {{gross_salary}} </br> <b>{{9101_desc}}</b> {{9101_value}} <b>{{9102_desc}}</b> {{9102_value}} <b>Total Salary:</b> {{total_salary}} </br> <b>{{599_desc}}</b> {{599_amt}} <b>{{307_desc}}</b> {{307_amt}} </br> <h2>Grand Total:</h2> {{grand_total}} </br> <hr> <h2>Deduction for {{date}}</h2> <b>{{305_desc}}</b> {{305_amt}} <b>{{370_desc}}</b> {{370_amt}} <b>{{374_desc}}</b> {{374_amt}} </br> <h2>Total Deduction:</h2>{{total_deduction}}`

csv file sent in slack.

**Expected behavior**
The empty spaces should have been removed. 

**Tablet (please complete the following information):**
iPad Pro, Safari

**Comment by lamkeewei** [comment]
Can't reproduce for now. Pending user to provide his exact input.

**Comment by lamkeewei** [comment]
Issue occurs when the line contains other tags. Example:

```
<b>{{value1}}</b>{{value1}}
<b>{{value1}}</b>{{value1}}
<b>{{value1}}</b>{{value1}}
hello
```

Even if remove new lines are enabled, it will not be removed as each line renders to `<b></b><br>` if `value1` is empty.
