### ISSUE TITLE
Resolve warnings to update lingui to remove use of React Legacy API

### ISSUE THREAD

**Issue by miazima** [opengovsg/postmangovsg#864]
**Describe the bug**
A warning is thrown by React that the `lingui` package is using a legacy api version of react. This legacy api will not be supported in the next major release of react. We should figure out if we can transition `lingui` from this version.

![image](https://user-images.githubusercontent.com/5744384/100312561-a233f200-2fed-11eb-8ed3-be673b2509f0.png)

**To Reproduce**

1. Load Postman landing/dashboard page and observe warnings in console

**Comment by miazima** [comment]
The repo maintainer has stated that the updated version which uses the new react context api has not been released yet. Putting this on hold till further updates from the lingui repo.

Refer https://github.com/lingui/js-lingui/issues/622#issuecomment-600772385

**Comment by zwliew** [comment]
Looks like the lingui v3 has been released. It is now at v3.5.1. Could I try fixing this issue?

**Comment by lamkeewei** [comment]
> Looks like the lingui v3 has been released. It is now at v3.5.1. Could I try fixing this issue?

Sure! Thanks!
