### ISSUE TITLE
Demo credentials appear in normal Telegram campaign creation

### ISSUE THREAD

**Issue by NatMaeTan** [opengovsg/postmangovsg#874]
**Describe the bug**
Postman demo credential automatically appears in Telegram stored credentials when creating normal campaign. It is defaulted when there are no other stored credentials. When trying to validate, an error message shows.

**To Reproduce**

1. Create a Telegram Demo Campaign
2. Go to Create New Campaign
3. Create Telegram Campaign
4. Move to Step 3: Insert Credentials
5. See error

**Expected behavior**
Demo credentials should not appear in normal creation flow at all. This error does not appear in normal SMS campaign creation. 

**Screenshots**
<img width="607" alt="Screenshot 2020-11-30 at 4 21 59 PM" src="https://user-images.githubusercontent.com/63220614/100713945-0c82d300-33f0-11eb-87fa-782343beba16.png">

**Comment by lamkeewei** [comment]
@NatMaeTan the demo credential is named "Postman_Telegram_Demo". I think this is a bot token you've saved/added previously. It does not appear in my list of Telegram credentials.

<img src='https://user-images.githubusercontent.com/3666479/100714965-7b146080-33f1-11eb-8e6d-c06db48bdf91.png' 
 width=500/>
