### ISSUE TITLE
Consolidate and clean up environment variables for serverless functions

### ISSUE THREAD

**Issue by lamkeewei** [opengovsg/postmangovsg#883]
**Is your feature request related to a problem? Please describe.**
There are too many environment variables for our lambda functions. Some could be duplicated.

**Describe the solution you'd like**
Store environment variables for lambdas as secrets in Secrets Manager. Potentially hardcode as default values for certain environment variables to prevent having to pass them in.

**Comment by jhibberd-gov** [comment]
Moved to Notion.
