### ISSUE TITLE
[Announcement Modal] Update design, add video support and version with content hash

### ISSUE THREAD

**Issue by theMogget** [opengovsg/postmangovsg#934]
For additional context on announcement modals refer to the initial issue #798 and PR #920 

### Problems
- Our current modal do not conform to the design
- Our current modal only support images and text as the content. However, some features may be better presented as a short video clip
- The current modal is versioned with the release version number (e.g. `v1.18.0`). This version number is currently stored in the lingui catalog and needs to be manually updated. There is also some confusion as to what to set this value to. For example, if the announcement is to be released with `v1.18.0`, the convention now is to set the version in `lingui` as `v1.17.2` (the last version before release) to allow for testing in staging. 

### Proposed solution
- Use the hash of the announcement content to version the announcement. This removes any confusion associated with the version number
- Update designed based on Figma screens (link in comment below)
- Add support for videos as the main content in the modal (refer to screenshots)

### Screenshots

**Current modal:**
![image](https://user-images.githubusercontent.com/18324242/103625943-8de0fe80-4f76-11eb-838a-912bfa31a0f9.png)

**New modal, video or image/text:**
![image](https://user-images.githubusercontent.com/18324242/103625873-815ca600-4f76-11eb-836e-276e28c9516a.png)

**Comment by NatMaeTan** [comment]
Figma can be viewed [here](https://www.figma.com/file/29FkTqWnA4yLKzstnvyY6X/%F0%9F%91%91Design-Master?node-id=5761%3A0)

**Comment by zwliew** [comment]
I have a few queries I hope to clarify:
1. In what context do we place the title on the upper left corner versus in the centre? For example, the [second modal in this issue](https://user-images.githubusercontent.com/18324242/103625873-815ca600-4f76-11eb-836e-276e28c9516a.png) has the title at the upper left corner, while the first modal in the [Figma link has it in the centre](https://www.figma.com/file/29FkTqWnA4yLKzstnvyY6X/%F0%9F%91%91Design-Master?node-id=5761%3A0).

**Comment by lamkeewei** [comment]
> I have a few queries I hope to clarify:
> 
> 1. In what context do we place the title on the upper left corner versus in the centre? For example, the [second modal in this issue](https://user-images.githubusercontent.com/18324242/103625873-815ca600-4f76-11eb-836e-276e28c9516a.png) has the title at the upper left corner, while the [first modal in the Figma link](https://www.figma.com/file/29FkTqWnA4yLKzstnvyY6X/%F0%9F%91%91Design-Master?node-id=5761%3A0) has it in the centre. Or should the modal accommodate both designs?

@sarahsalim what are you thoughts on this? 

> 2. What would be a good way to hash the announcement content, considering the announcement will support images and video?

Will depend on what variables would be exposed in the implementation. But maybe something like `hash($TITLE;$CONTENT_TEXT;$CONTENT_URL;)` where each field concatenated and delimited by a `;`.

**Comment by zwliew** [comment]
> > I have a few queries I hope to clarify:
> > 
> > 1. In what context do we place the title on the upper left corner versus in the centre? For example, the [second modal in this issue](https://user-images.githubusercontent.com/18324242/103625873-815ca600-4f76-11eb-836e-276e28c9516a.png) has the title at the upper left corner, while the [first modal in the Figma link](https://www.figma.com/file/29FkTqWnA4yLKzstnvyY6X/%F0%9F%91%91Design-Master?node-id=5761%3A0) has it in the centre. Or should the modal accommodate both designs?
> 
> @sarahsalim what are you thoughts on this?
> 
> > 1. What would be a good way to hash the announcement content, considering the announcement will support images and video?
> 
> Will depend on what variables would be exposed in the implementation. But maybe something like `hash($TITLE;$CONTENT_TEXT;$CONTENT_URL;)` where each field concatenated and delimited by a `;`.

Thanks! I'll work on the hashing change first since it seems the most straightforward right now.

I also have another doubt regarding embedding videos in the modal: would videos be embedded in the form of YouTube links, links to direct formats like MP4, or both? Embedding videos in direct formats like MP4 is pretty straightforward.

On the other hand, YouTube embeds require using an iframe to load a separate webpage (e.g. https://youtube.com/embed/VIDEO_HASH). The implementation would be more complicated as I would need to add an iframe to the announcement modal.

**Comment by zwliew** [comment]
I have also written a design doc (excluding video support for now) here: https://docs.google.com/document/d/1OfGiH2ygIiidG8vjVXFxEdWE_09ZM3QHwkkhbMXkwQQ

Please have a look and give feedback if any.

**Comment by sarahsalim** [comment]
Regarding titles placements on modals, if you see the latest figma link Natalie has shared earlier on the thread... 

1. For graphic and text modals, the title is underneath the image together with body text and buttons. 
2. For video modals, the title is at top left hand corner.

So yes, technically the modal has to accommodate two different title placements, depending on which content is used. 

Also, I think it’s better to embed videos directly? Using YouTube iframe sounds complicated. Only concern if it will load fast enough? What would be the maximum mp4 file size for the load performance to be still acceptable?

**Comment by zwliew** [comment]
> Regarding titles placements on modals, if you see the latest figma link Natalie has shared earlier on the thread...
> 
> 1. For graphic and text modals, the title is underneath the image together with body text and buttons.
> 2. For video modals, the title is at top left hand corner.
> 
> So yes, technically the modal has to accommodate two different title placements, depending on which content is used.
> 
> Also, I think it’s better to embed videos directly? Using YouTube iframe sounds complicated. Only concern if it will load fast enough? What would be the maximum mp4 file size for the load performance to be still acceptable?

Thanks for the clarification! I've made a PR that moves the title to the appropriate position according to the file extension of the media URL.

Regarding your concerns about load performance, I don't think the file size of the MP4 will affect the load performance of the modal, so there shouldn't be any issues there.
