### ISSUE TITLE
Clean up orphan credentials in Secrets Manager

### ISSUE THREAD

**Issue by lamkeewei** [opengovsg/postmangovsg#956]
**Is your feature request related to a problem? Please describe.**
Credentials are currently never deleted even when a user disassociate it with their account. These credentials cost us money to store in Secrets Manager.

**Describe the solution you'd like**
- Identify the credentials that are:
  - Not associated to any user in the database (found in `credentials` but not in `user_credentials`)
  - All campaigns using the credentials have already been sent 
  - Exists in Secrets Manager but not in the database
- Delete these credentials programmatically

**Comment by syan-syan** [comment]
1. tag every secret as stg or dev manually
2. remove unnecessary ones

**Comment by jhibberd-gov** [comment]
Moved to Notion.
