### ISSUE TITLE
Document lingui setup instructions

### ISSUE THREAD

**Issue by zwliew** [opengovsg/postmangovsg#981]
**Issue description**
Currently, it is not clear that the following commands need to be run in order to set up lingui:
1. `npm run extract`
2. `npm run compile`

Without running the aforementioned commands, `frontned/src/locales/en/messages.js`, which is a dependency of `frontend/src/locales/index.tsx` will be missing.

**Proposal**
Document the need to run the commands in [the setup instructions](https://github.com/opengovsg/postmangovsg#install-and-run-the-app) like so:
```bash
cd postmangovsg
npm install
cd frontend && npm run extract && npm run compile && cd ../
npm run dev
```

**Comment by lamkeewei** [comment]
I think there's existing docs on this but it's [buried in](https://github.com/opengovsg/postmangovsg/blob/develop/frontend/src/locales/README.md) the `locales` folder. 

Agree that we should move it into part of the setup process.
